schemaVersion: 2.0.0

metadataTest:
  labels:
    - key: "business.region"
      value: "Indonesia"
    - key: "business.currency"
      value: "IDR"
    - key: "business.timezone" 
      value: "Asia/Jakarta"
  exposedPorts: ["5000"]
  workdir: "/app"
  user: "appuser"
  env:
    - key: "NODE_ENV"
      value: "production"
    - key: "TZ"
      value: "Asia/Jakarta"
    - key: "DEFAULT_CURRENCY"
      value: "IDR"

fileExistenceTests:
  - name: "Backend application exists"
    path: "/app/backend/dist/main.js"
    shouldExist: true
  - name: "Frontend application exists"
    path: "/app/frontend/dist"
    shouldExist: true
  - name: "No .env files in production"
    path: "/app/.env"
    shouldExist: false

commandTests:
  - name: "Application runs as non-root user"
    command: "whoami"
    expectedOutput: ["appuser"]
  - name: "Node.js version check"
    command: "node"
    args: ["--version"]
    expectedOutput: ["v20\\..*"]
  - name: "Indonesian timezone configured"
    command: "date"
    args: ["+%Z"]
    expectedOutput: ["WIB"]
EOF < /dev/null
