version: '3.8'

services:
  # =============================================================================
  # BACKEND SERVICE (NestJS)
  # =============================================================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: monomi-backend-dev
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://invoiceuser:devpassword@db:5432/invoices
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-jwt-secret-key
      - TZ=Asia/Jakarta
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./storage:/app/storage
    networks:
      - invoice-network
    restart: unless-stopped
    command: npm run start:dev

  # =============================================================================
  # FRONTEND SERVICE (React + Vite)
  # =============================================================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: monomi-frontend-dev
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
      - VITE_APP_TITLE=Monomi Finance - Indonesian Business System
      - TZ=Asia/Jakarta
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - invoice-network
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

  # =============================================================================
  # DATABASE SERVICE (PostgreSQL)
  # =============================================================================
  db:
    image: postgres:15.4-alpine3.18
    container_name: monomi-db-dev
    environment:
      - POSTGRES_DB=invoices
      - POSTGRES_USER=invoiceuser
      - POSTGRES_PASSWORD=devpassword
      - TZ=Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./backup:/backup
    networks:
      - invoice-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invoiceuser -d invoices"]
      interval: 30s
      timeout: 10s
      retries: 5

  # =============================================================================
  # REDIS SERVICE (Session & Cache)
  # =============================================================================
  redis:
    image: redis:7.2.3-alpine3.18
    container_name: monomi-redis-dev
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - invoice-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  invoice-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local