/**
 * Cuts, encodes and packages the guide videos from the raw recordings made by
 * `node capture.mjs --record <flows>` (out/videos/raw + out/videos/timeline).
 *
 *   node build-videos.mjs                 every guide that has recorded steps
 *   node build-videos.mjs quotation invoice
 *
 * Per guide it writes to out/videos/dist/ (what upload-videos.mjs uploads):
 *   <slug>.<hash>.mp4            H.264 yuv420p, faststart, 30 fps, no audio track
 *   <slug>.<hash>.webp           poster (frame of step 1, highlight visible)
 *   <slug>.<hash>.id.vtt / .en.vtt           captions (step title + short instruction)
 *   <slug>.<hash>.chapters.id.vtt / .en.vtt  one cue per step, for seeking
 * plus the narration script narration/<slug>.md, and it updates
 * src/guides/videoManifest.ts (slug -> files, size, durations, step times).
 * File names carry a content hash, so they are immutable and cacheable for a year.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import sharp from 'sharp';
import { FRONTEND, HERE } from './lib.mjs';
import { OUT, TIMELINE_DIR } from './lib-record.mjs';
import { captionText, guideText, loadGuides, narrationText, speechRate, wordCount } from './guide-data.mjs';

export const DIST = path.join(OUT, 'dist');
export const VIDEO_MANIFEST_TS = path.join(FRONTEND, 'src', 'guides', 'videoManifest.ts');
const NARRATION_DIR = path.join(HERE, 'narration');
const CRF = Number(process.env.GUIDE_CRF || 28);
const DESKTOP_MAX_W = 1280;
const MOBILE_W = Number(process.env.GUIDE_MOBILE_W || 540);
const BG = '0x0b0b0b';

const args = process.argv.slice(2);
const wanted = args.filter((a) => !a.startsWith('--'));

const even = (n) => Math.max(2, Math.round(n / 2) * 2);
const sha = (buf) => crypto.createHash('sha256').update(buf).digest('hex').slice(0, 8);

function ffmpeg(argv) {
  const r = spawnSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', ...argv], { encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`ffmpeg failed: ${r.stderr}`);
}
function probeDuration(file) {
  const r = spawnSync('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', file], { encoding: 'utf8' });
  return Number(r.stdout.trim());
}

/* ---------------- manifest (src/guides/videoManifest.ts holds JSON) ---------------- */

function loadManifest() {
  try {
    const src = fs.readFileSync(VIDEO_MANIFEST_TS, 'utf8');
    const m = src.match(/guideVideoManifest[^=]*=\s*(\{[\s\S]*?\n\});/);
    if (m) return JSON.parse(m[1]);
  } catch { /* first run */ }
  return {};
}

function saveManifest(manifest) {
  const sorted = Object.fromEntries(Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)));
  const body = `/* GENERATED by frontend/scripts/guides/build-videos.mjs - do not edit by hand.
 * File names are relative to the video base URL (VITE_GUIDE_VIDEO_BASE, default
 * https://media.monomiagency.com/public-guides) and carry a content hash. */
export interface GuideVideoChapter {
  /** Step id (see guides data). */
  step: string;
  /** Seconds into the video. */
  start: number;
  end: number;
}

export interface GuideVideo {
  mp4: string;
  poster: string;
  /** Captions per UI language. */
  vtt: { id: string; en: string };
  /** Chapter tracks (one cue per step) per UI language. */
  chaptersVtt: { id: string; en: string };
  chapters: GuideVideoChapter[];
  /** Pixel size of the picture, so the player box never jumps. */
  w: number;
  h: number;
  durationSec: number;
  /** Hash of the MP4: changes whenever the video does. */
  version: string;
}

export const guideVideoManifest: Partial<Record<string, GuideVideo>> = ${JSON.stringify(sorted, null, 2)};
`;
  fs.mkdirSync(path.dirname(VIDEO_MANIFEST_TS), { recursive: true });
  fs.writeFileSync(VIDEO_MANIFEST_TS, body.replace(/\r\n/g, '\n'));
}

/* ---------------- timelines ---------------- */

function loadTimelines() {
  const stepsByGuide = {};
  if (!fs.existsSync(TIMELINE_DIR)) return stepsByGuide;
  for (const f of fs.readdirSync(TIMELINE_DIR).filter((x) => x.endsWith('.json')).sort()) {
    const tl = JSON.parse(fs.readFileSync(path.join(TIMELINE_DIR, f), 'utf8'));
    const pages = new Map(tl.pages.map((p) => [p.index, p]));
    for (const s of tl.steps) {
      const page = pages.get(s.page);
      if (!page || !page.video) continue;
      const file = path.join(OUT, page.video);
      if (!fs.existsSync(file)) continue;
      const dur = probeDuration(file) * 1000;
      // The recording ends when the page closes and starts a little before the page object existed.
      const skew = tl.pages.length > 0 && page.tClose ? (page.tClose - page.t0) - dur : 0;
      const toVideo = (ms) => (ms - page.t0 - skew) / 1000;
      (stepsByGuide[s.guide] ??= []).push({
        step: s.step, flow: tl.flow, page: page.index, file, w: page.w, h: page.h, mobile: page.mobile,
        start: toVideo(s.start), end: toVideo(s.end),
      });
    }
  }
  return stepsByGuide;
}

/* ---------------- one guide ---------------- */

const mmss = (sec) => `${String(Math.floor(sec / 60)).padStart(2, '0')}:${(sec % 60).toFixed(1).padStart(4, '0')}`;
const vttTime = (sec) => {
  const ms = Math.round(sec * 1000);
  const h = Math.floor(ms / 3600000);
  const m = Math.floor((ms % 3600000) / 60000);
  const s = Math.floor((ms % 60000) / 1000);
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(ms % 1000).padStart(3, '0')}`;
};

async function buildGuide(guide, recorded, manifest) {
  const order = new Map(guide.steps.map((id, i) => [id, i]));
  const steps = recorded.filter((s) => order.has(s.step)).sort((a, b) => order.get(a.step) - order.get(b.step));
  const missing = guide.steps.filter((id) => !steps.some((s) => s.step === id));
  if (steps.length === 0) return null;
  if (missing.length > 0) console.log(`  ! ${guide.slug}: no recording for step(s) ${missing.join(', ')}`);

  // Contiguous steps of one recording become one segment (cut exactly once).
  const segs = [];
  for (const s of steps) {
    const last = segs[segs.length - 1];
    if (last && last.file === s.file && Math.abs(s.start - last.end) < 0.05) {
      last.end = s.end;
      last.steps.push(s);
    } else {
      segs.push({ file: s.file, w: s.w, h: s.h, mobile: s.mobile, start: s.start, end: s.end, steps: [s] });
    }
  }

  // Output picture: the page that carries most of the guide decides the size; other pages are letterboxed.
  const weight = new Map();
  for (const s of steps) weight.set(s.file, (weight.get(s.file) ?? 0) + (s.end - s.start));
  const primary = steps.find((s) => s.file === [...weight.entries()].sort((a, b) => b[1] - a[1])[0][0]);
  const outW = primary.mobile ? MOBILE_W : Math.min(DESKTOP_MAX_W, primary.w);
  const outH = even((outW * primary.h) / primary.w);
  const W = even(outW);

  const filters = [];
  const inputs = [];
  segs.forEach((sg, i) => {
    const ss = Math.max(0, sg.start - 0.02);
    inputs.push('-ss', ss.toFixed(3), '-t', (sg.end - ss + 0.02).toFixed(3), '-i', sg.file);
    filters.push(`[${i}:v]setpts=PTS-STARTPTS,fps=30,scale=${W}:${outH}:flags=lanczos:force_original_aspect_ratio=decrease,pad=${W}:${outH}:(ow-iw)/2:(oh-ih)/2:color=${BG},setsar=1,format=yuv420p[v${i}]`);
  });
  filters.push(`${segs.map((_, i) => `[v${i}]`).join('')}concat=n=${segs.length}:v=1:a=0[out]`);

  fs.mkdirSync(DIST, { recursive: true });
  const tmp = path.join(DIST, `.${guide.slug}.tmp.mp4`);
  ffmpeg([
    ...inputs,
    '-filter_complex', filters.join(';'),
    '-map', '[out]',
    '-c:v', 'libx264', '-preset', 'slow', '-crf', String(CRF), '-pix_fmt', 'yuv420p', '-r', '30',
    '-profile:v', 'high', '-movflags', '+faststart', '-an', tmp,
  ]);
  const mp4Buf = fs.readFileSync(tmp);
  const version = sha(mp4Buf);
  const base = `${guide.slug}.${version}`;
  fs.renameSync(tmp, path.join(DIST, `${base}.mp4`));
  const duration = probeDuration(path.join(DIST, `${base}.mp4`));

  // Step times in the cut video: segments are laid end to end.
  const chapters = [];
  let offset = 0;
  for (const sg of segs) {
    const ss = Math.max(0, sg.start - 0.02);
    for (const s of sg.steps) {
      chapters.push({ step: s.step, start: +(offset + (s.start - ss)).toFixed(2), end: +(offset + (s.end - ss)).toFixed(2) });
    }
    offset += sg.end - ss + 0.02;
  }
  // Clamp the last cue to the real duration and make the first start at 0.
  chapters[0].start = 0;
  chapters[chapters.length - 1].end = +duration.toFixed(2);

  // Poster: the end of step 1 (highlight and badge visible).
  const t1 = Math.max(0, chapters[0].end - 0.5);
  const posterPng = path.join(DIST, `.${guide.slug}.poster.png`);
  ffmpeg(['-ss', t1.toFixed(2), '-i', path.join(DIST, `${base}.mp4`), '-frames:v', '1', posterPng]);
  await sharp(posterPng).webp({ quality: 74, effort: 5 }).toFile(path.join(DIST, `${base}.webp`));
  fs.unlinkSync(posterPng);

  // Captions + chapters per language.
  const vtt = {};
  const chaptersVtt = {};
  for (const lang of ['id', 'en']) {
    const cues = chapters.map((c) => `${vttTime(c.start)} --> ${vttTime(c.end)}\n${captionText(guide.slug, c.step, lang)}`);
    const capBody = `WEBVTT\n\n${cues.map((c, i) => `${i + 1}\n${c}`).join('\n\n')}\n`;
    const chBody = `WEBVTT\n\n${chapters.map((c, i) => `${i + 1}\n${vttTime(c.start)} --> ${vttTime(c.end)}\n${guideText(guide.slug, lang).steps[c.step].title}`).join('\n\n')}\n`;
    const capName = `${guide.slug}.${sha(capBody)}.${lang}.vtt`;
    const chName = `${guide.slug}.${sha(chBody)}.chapters.${lang}.vtt`;
    fs.writeFileSync(path.join(DIST, capName), capBody);
    fs.writeFileSync(path.join(DIST, chName), chBody);
    vtt[lang] = capName;
    chaptersVtt[lang] = chName;
  }

  manifest[guide.slug] = {
    mp4: `${base}.mp4`, poster: `${base}.webp`, vtt, chaptersVtt, chapters,
    w: W, h: outH, durationSec: +duration.toFixed(1), version,
  };
  writeNarration(guide, chapters, duration, `${base}.mp4`, W, outH);
  const mb = mp4Buf.length / 1048576;
  console.log(`  ${guide.slug}  ${W}x${outH}  ${mmss(duration)}  ${mb.toFixed(2)} MB  ${steps.length}/${guide.steps.length} steps${mb > 8 ? '  ** over 8 MB' : ''}`);
  return { slug: guide.slug, duration, bytes: mp4Buf.length };
}

/* ---------------- narration script ---------------- */

function writeNarration(guide, chapters, duration, mp4, w, h) {
  const idText = guideText(guide.slug, 'id');
  const enText = guideText(guide.slug, 'en');
  const lines = [];
  lines.push(`# Narasi / Narration: ${idText.title}`);
  lines.push('');
  lines.push(`Video: \`${mp4}\` (${w}x${h}, ${mmss(duration)}, silent). Guide slug: \`${guide.slug}\`.`);
  lines.push('');
  lines.push('Timestamps are mm:ss.s in the video. Each step has a window (from when the step starts until the next one starts) and a word budget at a calm speaking pace');
  lines.push(`(Indonesian about ${speechRate.id} words/second, English about ${speechRate.en}). The drafts are written to fit; shorten them or leave pauses rather than speed up.`);
  lines.push('The orange highlight and numbered badge appear a few seconds into each step, so name the thing the badge points at when it shows.');
  lines.push('');
  lines.push('Pembukaan (opsional, sebelum 00:00) / Opening (optional, before 00:00):');
  lines.push('');
  lines.push(`- ID: ${idText.purpose}`);
  lines.push(`- EN: ${enText.purpose}`);
  lines.push('');
  for (const [i, c] of chapters.entries()) {
    const win = c.end - c.start;
    const budget = (lang) => Math.floor((win - 0.4) * speechRate[lang]);
    const id = narrationText(guide.slug, c.step, 'id');
    const en = narrationText(guide.slug, c.step, 'en');
    const flag = (txt, lang) => (wordCount(txt) <= budget(lang) ? '' : ' (OVER BUDGET: trim a few words)');
    lines.push(`## Langkah ${i + 1} / Step ${i + 1}: ${idText.steps[c.step].title}`);
    lines.push('');
    lines.push(`- Window: ${mmss(c.start)} - ${mmss(c.end)} (${win.toFixed(1)} s)`);
    lines.push(`- ID (${wordCount(id)} of max ${budget('id')} words)${flag(id, 'id')}: ${id}`);
    lines.push(`- EN (${wordCount(en)} of max ${budget('en')} words)${flag(en, 'en')}: ${en}`);
    const tipId = idText.steps[c.step].tip;
    const tipEn = enText.steps[c.step].tip;
    if (tipId) lines.push(`- Tip (opsional / optional, only if there is time): ${tipId.replace(/"/g, '')} / ${(tipEn ?? '').replace(/"/g, '')}`);
    lines.push('');
  }
  fs.mkdirSync(NARRATION_DIR, { recursive: true });
  fs.writeFileSync(path.join(NARRATION_DIR, `${guide.slug}.md`), lines.join('\n'));
}

/* ---------------- main ---------------- */

async function main() {
  const guides = loadGuides();
  const timelines = loadTimelines();
  const manifest = loadManifest();
  const results = [];
  for (const g of guides) {
    if (wanted.length > 0 && !wanted.includes(g.slug)) continue;
    const recorded = timelines[g.slug];
    if (!recorded) continue;
    const r = await buildGuide(g, recorded, manifest);
    if (r) results.push(r);
  }
  saveManifest(manifest);
  const total = results.reduce((n, r) => n + r.bytes, 0);
  console.log(`\n${results.length} video(s), ${(total / 1048576).toFixed(2)} MB total in ${path.relative(process.cwd(), DIST)}`);
  console.log(`manifest: ${path.relative(process.cwd(), VIDEO_MANIFEST_TS)}`);
}

main().catch((e) => { console.error(e); process.exitCode = 1; });
