import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  AlertTriangle, ChevronLeft, ChevronRight, Eye, Layout as LayoutIcon,
  Download, Loader2, MessageSquare, Send,
} from 'lucide-react';
import { toast } from 'sonner';
import { AuroraBackground } from '@/components/monomi/AuroraBackground';
import { GlassPanel } from '@/components/monomi/GlassPanel';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Input } from '@/components/ui/input';
import { decksApi } from '@/services/decks';
import type { DeckSlide, DeckSlideComment } from '@/types/deck';
import { cn } from '@/lib/utils';
import { safeUrl } from '@/utils/safeUrl';

/* ------------------------------------------------------------------ */
/*  PublicDeckViewPage                                                  */
/*                                                                      */
/*  Public (no-auth) deck viewer. URL: /deck/shared/:token             */
/*  Matches the URL generated by deck-share.util.ts:                   */
/*    `${FRONTEND_URL}/deck/shared/${token}`                            */
/*                                                                      */
/*  Renders the deck's slides READ-ONLY (no editing controls, no auth  */
/*  chrome). Matches the look/feel of PublicProjectViewPage.            */
/* ------------------------------------------------------------------ */

export const PublicDeckViewPage = () => {
  const { t } = useTranslation();
  const { token } = useParams<{ token: string }>();
  const [activeSlideIndex, setActiveSlideIndex] = useState(0);
  const [exportJobId, setExportJobId] = useState<string | null>(null);
  const [exportStatus, setExportStatus] = useState<'idle' | 'pending' | 'processing' | 'completed' | 'failed'>('idle');
  const queryClient = useQueryClient();

  /* ----- data ----- */
  const {
    data: deck,
    isLoading,
    error,
  } = useQuery({
    queryKey: ['public-deck', token],
    queryFn: () => decksApi.getPublic(token!),
    enabled: !!token,
    retry: false,
  });

  /* ----- PDF export (DOWNLOAD level) ----- */
  const exportMutation = useMutation({
    mutationFn: () => decksApi.startPublicExportPdf(token!),
    onSuccess: (data) => {
      setExportJobId(data.jobId);
      setExportStatus('pending');
    },
    onError: (err: Error) => {
      toast.error(err.message || t('deckPublic.exportFailed', 'Export failed'));
    },
  });

  // Poll export job status until complete
  useEffect(() => {
    if (!exportJobId || exportStatus === 'idle' || exportStatus === 'completed' || exportStatus === 'failed') return;

    const interval = setInterval(async () => {
      try {
        const status = await decksApi.getPublicExportPdfStatus(token!, exportJobId);
        setExportStatus(status.status as typeof exportStatus);
        if (status.status === 'completed') {
          clearInterval(interval);
          toast.success(t('deckPublic.exportReady', 'PDF is ready — check your downloads'));
          // Open authenticated download URL — the job lives on the server briefly
          // Redirect to the backend download endpoint (public download via jobId)
          window.open(`/api/decks/${deck?.id}/export/pdf/download/${exportJobId}`, '_blank');
        } else if (status.status === 'failed') {
          clearInterval(interval);
          toast.error(t('deckPublic.exportFailed', 'Export failed'));
        }
      } catch {
        clearInterval(interval);
        setExportStatus('failed');
      }
    }, 2000);

    return () => clearInterval(interval);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [exportJobId, exportStatus, token]);

  /* ----- keyboard navigation ----- */
  useEffect(() => {
    const slides = deck?.slides ?? [];
    if (slides.length === 0) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
        e.preventDefault();
        setActiveSlideIndex((i) => Math.min(i + 1, slides.length - 1));
      } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
        e.preventDefault();
        setActiveSlideIndex((i) => Math.max(i - 1, 0));
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [deck?.slides]);

  /* ----- missing or invalid token ----- */
  if (!token) {
    return (
      <ShellFrame>
        <ErrorPanel
          title={t('guest.publicDeckView.incompleteLink', 'Tautan Tidak Lengkap')}
          body={t('guest.publicDeckView.incompleteLinkBody', 'Tautan berbagi ini terlihat rusak atau tidak lengkap. Mintalah pengirim untuk membagikan ulang tautan.')}
        />
      </ShellFrame>
    );
  }

  if (error) {
    return (
      <ShellFrame>
        <ErrorPanel
          title={t('guest.publicDeckView.deckNotFound', 'Deck Tidak Ditemukan')}
          body={t('guest.publicDeckView.deckNotFoundBody', 'Tautan publik ini tidak valid atau telah dinonaktifkan oleh pemiliknya.')}
        />
      </ShellFrame>
    );
  }

  /* ----- sorted slides ----- */
  const slides = [...(deck?.slides ?? [])].sort((a, b) => a.order - b.order);
  const activeSlide = slides[activeSlideIndex] ?? null;
  const totalSlides = slides.length;

  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-bg-base">
      <AuroraBackground />

      {/* ─────────────── Hero header bar ─────────────── */}
      <header className="relative z-10 border-b border-border-subtle bg-bg-base/60 backdrop-blur-[12px]">
        <div className="mx-auto flex max-w-[1280px] flex-col gap-3 px-6 py-5 sm:flex-row sm:items-center sm:justify-between">
          <div className="min-w-0">
            <div className="flex items-center gap-3">
              <span className="font-display text-xl font-semibold tracking-tight text-text-primary">
                monomi
              </span>
              <span className="h-4 w-px bg-border-default" />
              <span className="text-[10px] uppercase tracking-[0.2em] text-text-tertiary">
                {t('deckPublic.eyebrow', 'Public Deck')}
              </span>
            </div>
            {isLoading ? (
              <Skeleton className="mt-2 h-5 w-72 rounded" />
            ) : (
              <h1 className="mt-1 truncate text-base font-medium text-text-primary sm:text-lg">
                {deck?.title ?? '—'}
              </h1>
            )}
          </div>

          {/* Right rail: slide count + view count + download */}
          <div className="flex items-center gap-2">
            {deck && (
              <>
                <Badge
                  variant="outline"
                  className="border-info/30 bg-info/[0.08] text-info gap-1.5 px-2.5 py-1 text-xs"
                >
                  <LayoutIcon className="h-3 w-3" />
                  {t('deckPublic.slideCount', '{{count}} slide', { count: totalSlides })}
                </Badge>
                <Badge
                  variant="outline"
                  className="border-info/30 bg-info/[0.08] text-info gap-1.5 px-2.5 py-1 text-xs"
                >
                  <Eye className="h-3 w-3" />
                  {t('deckPublic.viewCount', '{{count}} views', { count: deck.publicViewCount ?? 0 })}
                </Badge>

                {/* Download button — only when DOWNLOAD access level */}
                {deck.publicAccessLevel === 'DOWNLOAD' && (
                  <Button
                    variant="outline"
                    size="sm"
                    disabled={exportMutation.isPending || exportStatus === 'pending' || exportStatus === 'processing'}
                    onClick={() => {
                      setExportStatus('idle');
                      setExportJobId(null);
                      exportMutation.mutate();
                    }}
                    className="gap-1.5 text-xs h-8"
                  >
                    {(exportMutation.isPending || exportStatus === 'pending' || exportStatus === 'processing')
                      ? <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      : <Download className="h-3.5 w-3.5" />}
                    {t('deckPublic.exportPdf', 'Export PDF')}
                  </Button>
                )}
              </>
            )}
          </div>
        </div>
      </header>

      {/* ─────────────── Main content ─────────────── */}
      <main className="relative z-10 mx-auto max-w-[1280px] px-4 sm:px-6 py-8">
        {/* Description card */}
        {deck?.description && (
          <GlassPanel surface="subtle" padding="md" className="mb-5">
            <div className="text-[10px] uppercase tracking-[0.16em] text-text-tertiary font-medium mb-1.5">
              {t('deckPublic.aboutThisDeck', 'About this deck')}
            </div>
            <p className="text-sm text-text-secondary leading-relaxed">
              {deck.description}
            </p>
          </GlassPanel>
        )}

        {isLoading ? (
          <GlassPanel surface="glass" padding="lg">
            <Skeleton className="aspect-video w-full rounded-md" />
          </GlassPanel>
        ) : totalSlides === 0 ? (
          <GlassPanel surface="glass" padding="lg" className="flex flex-col items-center justify-center py-16 text-center">
            <LayoutIcon className="h-10 w-10 text-text-tertiary mb-3" strokeWidth={1.25} />
            <p className="text-base font-medium text-text-primary">Deck ini belum memiliki slide</p>
            <p className="mt-1 text-sm text-text-tertiary">Pemilik belum menambahkan konten.</p>
          </GlassPanel>
        ) : (
          <div className="flex flex-col gap-5 lg:flex-row lg:items-start">
            {/* ── Slide thumbnail sidebar ── */}
            <aside className="w-full lg:w-52 shrink-0">
              <GlassPanel surface="glass" padding="none" className="overflow-hidden">
                <div className="border-b border-border-subtle px-4 py-3">
                  <span className="text-[10px] uppercase tracking-[0.16em] text-text-tertiary font-medium">
                    Slide
                  </span>
                  <span className="ml-2 text-[11px] tabular-nums text-text-tertiary">
                    {totalSlides}
                  </span>
                </div>
                <div className="divide-y divide-border-subtle">
                  {slides.map((slide, idx) => (
                    <SlideThumbnailButton
                      key={slide.id}
                      slide={slide}
                      index={idx}
                      isActive={idx === activeSlideIndex}
                      onClick={() => setActiveSlideIndex(idx)}
                    />
                  ))}
                </div>
              </GlassPanel>
            </aside>

            {/* ── Active slide canvas ── */}
            <div className="flex-1 min-w-0">
              {activeSlide && (
                <GlassPanel surface="glass" padding="none" className="overflow-hidden">
                  {/* Slide header */}
                  <div className="flex items-center justify-between gap-3 border-b border-border-subtle px-5 py-3">
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] uppercase tracking-[0.16em] text-text-tertiary font-medium">
                        Slide {activeSlideIndex + 1}/{totalSlides}
                      </span>
                      <span className="text-[10px] uppercase tracking-[0.12em] text-text-tertiary opacity-60">
                        {activeSlide.template}
                      </span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Button
                        variant="ghost"
                        size="icon-sm"
                        disabled={activeSlideIndex === 0}
                        onClick={() => setActiveSlideIndex((i) => Math.max(i - 1, 0))}
                        aria-label="Slide sebelumnya"
                        className="text-text-tertiary hover:text-text-primary disabled:opacity-30"
                      >
                        <ChevronLeft className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon-sm"
                        disabled={activeSlideIndex === totalSlides - 1}
                        onClick={() => setActiveSlideIndex((i) => Math.min(i + 1, totalSlides - 1))}
                        aria-label="Slide berikutnya"
                        className="text-text-tertiary hover:text-text-primary disabled:opacity-30"
                      >
                        <ChevronRight className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>

                  {/* Slide body */}
                  <SlideCanvas slide={activeSlide} />

                  {/* Slide notes */}
                  {activeSlide.notes && (
                    <div className="border-t border-border-subtle bg-bg-sunken/40 px-5 py-3">
                      <div className="text-[10px] uppercase tracking-[0.16em] text-text-tertiary font-medium mb-1">
                        Catatan
                      </div>
                      <p className="text-xs text-text-secondary leading-relaxed whitespace-pre-wrap">
                        {activeSlide.notes}
                      </p>
                    </div>
                  )}
                </GlassPanel>
              )}

              {/* Keyboard hint */}
              <p className="mt-3 text-center text-[11px] text-text-tertiary">
                {t('deckPublic.navHint', 'Use ← → to navigate between slides')}
              </p>
            </div>
          </div>
        )}

        {/* Comment panel — only when COMMENT access level */}
        {deck && deck.publicAccessLevel === 'COMMENT' && activeSlide && token && (
          <PublicCommentPanel
            token={token}
            slideId={activeSlide.id}
            onInvalidate={() => queryClient.invalidateQueries({ queryKey: ['public-deck-comments', token, activeSlide.id] })}
          />
        )}

        <div className="mt-8 text-center text-[11px] uppercase tracking-[0.18em] text-text-tertiary">
          Powered by Monomi · Deck Viewer
        </div>
      </main>
    </div>
  );
};

/* ------------------------------------------------------------------ */
/*  PublicCommentPanel — comment list + form for COMMENT access level. */
/* ------------------------------------------------------------------ */

function PublicCommentPanel({
  token,
  slideId,
  onInvalidate,
}: {
  token: string;
  slideId: string;
  onInvalidate: () => void;
}) {
  const { t } = useTranslation();
  const [guestName, setGuestName] = useState('');
  const [commentText, setCommentText] = useState('');

  const { data: comments = [], isLoading } = useQuery<DeckSlideComment[]>({
    queryKey: ['public-deck-comments', token, slideId],
    queryFn: () => decksApi.getPublicComments(token, slideId),
    retry: false,
  });

  const postMutation = useMutation({
    mutationFn: () =>
      decksApi.createPublicComment(token, {
        slideId,
        content: commentText.trim(),
        guestName: guestName.trim() || undefined,
      }),
    onSuccess: () => {
      setCommentText('');
      onInvalidate();
      toast.success(t('deckPublic.commentPosted', 'Comment posted'));
    },
    onError: (err: Error) => {
      toast.error(err.message || t('deckPublic.commentFailed', 'Failed to post comment'));
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!commentText.trim()) return;
    postMutation.mutate();
  };

  return (
    <GlassPanel surface="subtle" padding="md" className="mt-5">
      <div className="text-[10px] uppercase tracking-[0.16em] text-text-tertiary font-medium mb-3 flex items-center gap-1.5">
        <MessageSquare className="h-3 w-3" />
        {t('deckPublic.commentsTitle', 'Comments')}
        <span className="ml-1 text-text-tertiary/60">— {t('deckPublic.currentSlide', 'this slide')}</span>
      </div>

      {/* Existing comments */}
      {isLoading ? (
        <div className="flex items-center justify-center py-4 text-text-tertiary">
          <Loader2 className="h-4 w-4 animate-spin" />
        </div>
      ) : comments.length === 0 ? (
        <p className="text-xs text-text-tertiary py-2 mb-3">
          {t('deckPublic.noComments', 'No comments yet. Be the first!')}
        </p>
      ) : (
        <div className="space-y-2 mb-4 max-h-48 overflow-y-auto">
          {comments.map((c) => (
            <div key={c.id} className="rounded-md border border-border-subtle bg-bg-sunken/40 px-3 py-2">
              <div className="flex items-center gap-2 mb-0.5">
                <span className="text-xs font-medium text-text-primary">
                  {c.user?.name || c.guestName || t('deckPublic.guest', 'Guest')}
                </span>
                <span className="text-[10px] text-text-tertiary">
                  {new Date(c.createdAt).toLocaleDateString()}
                </span>
              </div>
              <p className="text-xs text-text-secondary leading-relaxed">{c.content}</p>
            </div>
          ))}
        </div>
      )}

      {/* Comment form */}
      <form onSubmit={handleSubmit} className="space-y-2">
        <Input
          value={guestName}
          onChange={(e) => setGuestName(e.target.value)}
          placeholder={t('deckPublic.namePlaceholder', 'Your name (optional)')}
          className="bg-bg-sunken border-border-default text-text-primary h-8 text-xs"
        />
        <div className="flex gap-2">
          <Input
            value={commentText}
            onChange={(e) => setCommentText(e.target.value)}
            placeholder={t('deckPublic.commentPlaceholder', 'Leave a comment…')}
            className="flex-1 bg-bg-sunken border-border-default text-text-primary h-8 text-xs"
          />
          <Button
            type="submit"
            size="sm"
            disabled={!commentText.trim() || postMutation.isPending}
            className="shrink-0 h-8"
          >
            {postMutation.isPending
              ? <Loader2 className="h-3.5 w-3.5 animate-spin" />
              : <Send className="h-3.5 w-3.5" />}
          </Button>
        </div>
      </form>
    </GlassPanel>
  );
}

/* ------------------------------------------------------------------ */
/*  SlideCanvas — read-only rendering of a single slide.               */
/*  Handles every SlideTemplate by progressively rendering what's      */
/*  available: backgroundImage, title, subtitle, content fields, and   */
/*  free-form elements (TEXT/IMAGE).                                    */
/* ------------------------------------------------------------------ */

function SlideCanvas({ slide }: { slide: DeckSlide }) {
  const { title, subtitle, content = {}, backgroundColor, backgroundImage, elements = [] } = slide;

  const slideStyle: React.CSSProperties = {
    backgroundColor: backgroundColor || undefined,
  };

  // Content field helpers — the schema stores arbitrary JSON in `content`.
  // Common keys used by the editor: body, caption, leftContent, rightContent,
  // images (array), items (array of strings), columns (array).
  const body: string | undefined = content.body;
  const caption: string | undefined = content.caption;
  const leftContent: string | undefined = content.leftContent;
  const rightContent: string | undefined = content.rightContent;
  const items: string[] | undefined = Array.isArray(content.items) ? content.items : undefined;
  const images: { url?: string; caption?: string }[] | undefined = Array.isArray(content.images) ? content.images : undefined;

  return (
    <div
      className="relative w-full overflow-hidden"
      style={slideStyle}
    >
      {/* Background image — full-bleed, object-cover */}
      {safeUrl(backgroundImage) && (
        <img
          src={safeUrl(backgroundImage)}
          alt="Latar belakang slide"
          className="pointer-events-none absolute inset-0 h-full w-full object-cover select-none"
          aria-hidden="true"
        />
      )}

      {/* Content layer */}
      <div
        className={cn(
          'relative z-10 flex min-h-[360px] flex-col gap-4 p-8',
          backgroundImage && 'bg-bg-base/60 backdrop-blur-[2px]',
          slide.template === 'TWO_COLUMN' && 'lg:flex-row lg:gap-8',
          slide.template === 'FULL_MEDIA' && 'items-center justify-center text-center',
          (slide.template === 'TITLE' || slide.template === 'BLANK') && 'items-center justify-center text-center',
        )}
      >
        {/* Title */}
        {title && (
          <h2 className={cn(
            'font-display font-semibold tracking-tight text-text-primary',
            slide.template === 'TITLE' ? 'text-3xl sm:text-4xl' : 'text-xl sm:text-2xl',
          )}>
            {title}
          </h2>
        )}

        {/* Subtitle */}
        {subtitle && (
          <p className="text-sm text-text-secondary leading-relaxed -mt-2">
            {subtitle}
          </p>
        )}

        {/* Two-column layout */}
        {slide.template === 'TWO_COLUMN' && (leftContent || rightContent) && (
          <div className="flex flex-col gap-4 lg:flex-row lg:gap-8 flex-1">
            {leftContent && (
              <div className="flex-1 text-sm text-text-secondary leading-relaxed whitespace-pre-wrap">
                {leftContent}
              </div>
            )}
            {rightContent && (
              <div className="flex-1 text-sm text-text-secondary leading-relaxed whitespace-pre-wrap">
                {rightContent}
              </div>
            )}
          </div>
        )}

        {/* Body text (TITLE_CONTENT, BLANK, etc.) */}
        {body && slide.template !== 'TWO_COLUMN' && (
          <p className="text-sm text-text-secondary leading-relaxed whitespace-pre-wrap">
            {body}
          </p>
        )}

        {/* Caption */}
        {caption && (
          <p className="text-xs text-text-tertiary leading-relaxed italic">
            {caption}
          </p>
        )}

        {/* Bullet list items */}
        {items && items.length > 0 && (
          <ul className="space-y-1.5 text-sm text-text-secondary">
            {items.map((item, i) => (
              <li key={i} className="flex items-start gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
                <span className="leading-relaxed">{item}</span>
              </li>
            ))}
          </ul>
        )}

        {/* Image grid (MOOD_BOARD, GRID_4, GRID_6, etc.) */}
        {images && images.length > 0 && (
          <div className={cn(
            'grid gap-2',
            images.length === 1 ? 'grid-cols-1' :
            images.length <= 4 ? 'grid-cols-2' : 'grid-cols-3',
          )}>
            {images.map((img, i) => safeUrl(img.url) && (
              <div key={i} className="overflow-hidden rounded-md border border-border-subtle bg-bg-sunken">
                <img
                  src={safeUrl(img.url)}
                  alt={img.caption ?? `Gambar ${i + 1}`}
                  loading="lazy"
                  className="h-full w-full object-cover"
                />
                {img.caption && (
                  <div className="px-2 py-1.5 text-[11px] text-text-tertiary truncate">
                    {img.caption}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Free-form elements: TEXT and IMAGE only (no pointer events for edit) */}
        {elements.length > 0 && (
          <div className="relative mt-4 min-h-[120px] w-full select-none">
            {elements
              .filter((el) => el.type === 'TEXT' || el.type === 'IMAGE')
              .sort((a, b) => a.zIndex - b.zIndex)
              .map((el) => (
                <div
                  key={el.id}
                  style={{
                    position: 'absolute',
                    left: el.x,
                    top: el.y,
                    width: el.width,
                    height: el.height,
                    transform: `rotate(${el.rotation}deg)`,
                    zIndex: el.zIndex,
                    pointerEvents: 'none',
                  }}
                >
                  {el.type === 'TEXT' && el.content?.text && (
                    <span
                      style={{
                        fontSize: el.content.fontSize ?? 14,
                        color: el.content.color ?? 'inherit',
                        fontWeight: el.content.bold ? 'bold' : undefined,
                        fontStyle: el.content.italic ? 'italic' : undefined,
                      }}
                      className="text-text-primary"
                    >
                      {el.content.text}
                    </span>
                  )}
                  {el.type === 'IMAGE' && safeUrl(el.content?.url) && (
                    <img
                      src={safeUrl(el.content.url)}
                      alt={el.content.alt ?? ''}
                      loading="lazy"
                      className="h-full w-full object-contain"
                    />
                  )}
                </div>
              ))}
          </div>
        )}

        {/* Empty slide fallback */}
        {!title && !subtitle && !body && !items && !images && !caption && elements.length === 0 && !leftContent && !rightContent && (
          <div className="flex flex-1 items-center justify-center text-text-tertiary">
            <LayoutIcon className="h-8 w-8 opacity-30" strokeWidth={1.25} />
          </div>
        )}
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  SlideThumbnailButton — sidebar thumbnail for each slide.           */
/* ------------------------------------------------------------------ */

function SlideThumbnailButton({
  slide,
  index,
  isActive,
  onClick,
}: {
  slide: DeckSlide;
  index: number;
  isActive: boolean;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        'w-full px-4 py-3 text-left transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-accent/60',
        isActive
          ? 'bg-accent/[0.10] border-l-2 border-l-accent'
          : 'hover:bg-bg-sunken/60 border-l-2 border-l-transparent',
      )}
    >
      <div className="flex items-center gap-2">
        <span className={cn(
          'shrink-0 text-[11px] tabular-nums font-medium',
          isActive ? 'text-accent' : 'text-text-tertiary',
        )}>
          {index + 1}
        </span>
        <div className="min-w-0">
          <div className={cn(
            'truncate text-xs font-medium',
            isActive ? 'text-text-primary' : 'text-text-secondary',
          )}>
            {slide.title ?? `Slide ${index + 1}`}
          </div>
          <div className="text-[10px] uppercase tracking-[0.12em] text-text-tertiary truncate">
            {slide.template}
          </div>
        </div>
      </div>
    </button>
  );
}

/* ------------------------------------------------------------------ */
/*  ShellFrame — empty aurora frame for non-rendering states.          */
/* ------------------------------------------------------------------ */

function ShellFrame({ children }: { children: React.ReactNode }) {
  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-bg-base">
      <AuroraBackground />
      <div className="absolute top-6 right-8 z-10 text-[10px] uppercase tracking-[0.2em] text-text-tertiary">
        Monomi Studio · Deck Publik
      </div>
      <div className="relative z-10 flex min-h-screen items-center justify-center px-4 py-10">
        {children}
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  ErrorPanel — mirrors the one in PublicProjectViewPage.             */
/* ------------------------------------------------------------------ */

function ErrorPanel({ title, body }: { title: string; body: string }) {
  return (
    <GlassPanel surface="strong" padding="lg" className="w-full max-w-[460px]">
      <div className="mb-6">
        <div className="text-[10px] uppercase tracking-[0.2em] text-text-tertiary mb-2">
          Deck Publik
        </div>
        <h1 className="text-[36px] leading-none font-display font-semibold text-text-primary tracking-tight">
          monomi
        </h1>
      </div>
      <div className="rounded-md border border-danger/25 bg-danger/[0.06] px-4 py-3">
        <div className="flex items-center gap-2 mb-1 text-danger">
          <AlertTriangle className="h-5 w-5" />
          <span className="text-[10px] uppercase tracking-[0.16em] font-medium">
            Tidak Dapat Dibuka
          </span>
        </div>
        <h2 className="text-base font-display font-semibold tracking-tight text-text-primary">
          {title}
        </h2>
        <p className="mt-1 text-xs text-text-secondary leading-relaxed">
          {body}
        </p>
      </div>
    </GlassPanel>
  );
}

export default PublicDeckViewPage;
