services:
  db-test:
    image: postgres:15-alpine
    container_name: invoice-db-test
    environment:
      POSTGRES_DB: invoices_test
      POSTGRES_USER: invoiceuser
      POSTGRES_PASSWORD: invoicepass
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invoiceuser -d invoices_test"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-test:
    image: redis:7-alpine
    container_name: invoice-redis-test
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_test_data: