# =============================================================================
# PROMETHEUS CONFIGURATION
# Monomi Finance - Indonesian Business Management System Monitoring
# =============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'monomi-finance'
    environment: 'production'
    region: 'indonesia'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL Exporter - Database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis Exporter - Cache metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx Exporter - Web server metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Monomi Finance Application - Backend metrics
  - job_name: 'monomi-backend'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Monomi Finance Application - Frontend metrics
  - job_name: 'monomi-frontend'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker Engine metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # BlackBox Exporter - Service health checks
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://host.docker.internal:3000    # Frontend
        - http://host.docker.internal:5000    # Backend
        - http://host.docker.internal:80      # Nginx
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom Indonesian business metrics
  - job_name: 'monomi-business-metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics/business'
    scrape_interval: 60s
    scrape_timeout: 30s
    params:
      format: ['prometheus']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'monomi_invoice_.*'
        target_label: 'business_type'
        replacement: 'invoice'
      - source_labels: [__name__]
        regex: 'monomi_quotation_.*'
        target_label: 'business_type'
        replacement: 'quotation'
      - source_labels: [__name__]
        regex: 'monomi_materai_.*'
        target_label: 'business_type'
        replacement: 'materai'

# Storage and performance configuration is handled via command line flags

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write.example.com/api/v1/write"
#     basic_auth:
#       username: "monomi-finance"
#       password: "secure-password"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'monomi_.*'
#         action: keep