import { normalizeRefCode } from "./ref-code";
import { normalizeInstagramHandle } from "./track-utils";

/** Landing-page answers: stored and shown as plain text only. */
export const BRAND_NAME_MAX = 80;
export const CATEGORY_MAX = 40;

/** Hard cap for the request body (sendBeacon payloads are tiny). */
export const TRACK_EVENT_MAX_BYTES = 4096;

/** The only events the endpoint accepts (and Meta ever receives from the page). */
export const TRACK_EVENT_NAMES = ["PageView", "ViewContent", "EngagedVisit", "Lead"] as const;
export type TrackEventName = (typeof TRACK_EVENT_NAMES)[number];

export interface ParsedTrackEvent {
  name: TrackEventName;
  visitId: string;
  /** CAPI event_id (generated by the snippet, one per event). */
  eventId: string;
  /** Lead only: the code written into the WhatsApp text. */
  ref: string | null;
  pageUrl: string | null;
  referrer: string | null;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  utmContent: string | null;
  utmTerm: string | null;
  fbclid: string | null;
  fbc: string | null;
  fbp: string | null;
  instagramHandle: string | null;
  brandName: string | null;
  category: string | null;
}

const ID_RE = /^[A-Za-z0-9_-]{8,64}$/;
const FBCLID_RE = /^[A-Za-z0-9_.-]{4,300}$/;
const FBC_RE = /^fb\.\d{1,2}\.\d{10,16}\.[A-Za-z0-9_.-]{4,300}$/;
const FBP_RE = /^fb\.\d{1,2}\.\d{10,16}\.\d{4,20}$/;

// eslint-disable-next-line no-control-regex
const CONTROL = /[\u0000-\u001f\u007f\u2028\u2029]/g;

/** Trimmed single-line string within a length cap, else null. */
function text(value: unknown, max: number): string | null {
  if (typeof value !== "string") return null;
  const v = value.replace(CONTROL, " ").replace(/\s+/g, " ").trim();
  return v ? v.slice(0, max) : null;
}

/** http(s) URL without fragment / credentials, capped; anything else is dropped. */
function url(value: unknown, max: number): string | null {
  if (typeof value !== "string" || value.length > 2000) return null;
  try {
    const u = new URL(value.trim());
    if (u.protocol !== "https:" && u.protocol !== "http:") return null;
    u.hash = "";
    u.username = "";
    u.password = "";
    return u.toString().slice(0, max);
  } catch {
    return null;
  }
}

function pattern(value: unknown, re: RegExp): string | null {
  return typeof value === "string" && re.test(value) ? value : null;
}

/**
 * Strict parse of the beacon body (raw text from sendBeacon, or an object).
 * Required: a whitelisted `name`, `visitId`, `eventId`, and for `Lead` a valid
 * `ref`. Everything else is sanitised or dropped; unknown keys are ignored and
 * never stored. Returns null for anything invalid (callers answer a generic 400).
 */
export function parseTrackEvent(raw: unknown): ParsedTrackEvent | null {
  let body: unknown = raw;
  if (typeof raw === "string") {
    if (Buffer.byteLength(raw, "utf8") > TRACK_EVENT_MAX_BYTES) return null;
    try {
      body = JSON.parse(raw);
    } catch {
      return null;
    }
  }
  if (!body || typeof body !== "object" || Array.isArray(body)) return null;
  const b = body as Record<string, unknown>;

  const name = TRACK_EVENT_NAMES.find((n) => n === b.name);
  const visitId = pattern(b.visitId, ID_RE);
  const eventId = pattern(b.eventId, ID_RE);
  if (!name || !visitId || !eventId) return null;
  const ref = normalizeRefCode(b.ref);
  if (name === "Lead" && !ref) return null;

  const utm =
    b.utm && typeof b.utm === "object" && !Array.isArray(b.utm)
      ? (b.utm as Record<string, unknown>)
      : {};
  const meta =
    b.meta && typeof b.meta === "object" && !Array.isArray(b.meta)
      ? (b.meta as Record<string, unknown>)
      : {};

  return {
    name,
    visitId,
    eventId,
    ref: name === "Lead" ? ref : null,
    pageUrl: url(b.pageUrl, 500),
    referrer: url(b.referrer, 500),
    utmSource: text(utm.source, 120),
    utmMedium: text(utm.medium, 120),
    utmCampaign: text(utm.campaign, 120),
    utmContent: text(utm.content, 120),
    utmTerm: text(utm.term, 120),
    fbclid: pattern(b.fbclid, FBCLID_RE),
    fbc: pattern(b.fbc, FBC_RE),
    fbp: pattern(b.fbp, FBP_RE),
    // qualifier answers only matter on the WhatsApp tap
    instagramHandle: name === "Lead" ? normalizeInstagramHandle(meta.instagram) : null,
    brandName: name === "Lead" ? text(meta.brandName, BRAND_NAME_MAX) : null,
    category: name === "Lead" ? text(meta.category, CATEGORY_MAX) : null,
  };
}
