# =============================================================================
# GRAFANA DATASOURCE PROVISIONING
# Monomi Finance - Indonesian Business Management System
# =============================================================================

apiVersion: 1

datasources:
  # =============================================================================
  # PROMETHEUS - METRICS DATA SOURCE
  # =============================================================================
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "GET"
      manageAlerts: true
      alertmanagerUid: "alertmanager"
      prometheusType: "Prometheus"
      prometheusVersion: "2.48.1"
      cacheLevel: "High"
      incrementalQueryOverlapWindow: "10m"
      exemplarTraceIdDestinations:
        - name: "Jaeger"
          url: "http://localhost:16686/trace/{{__value.raw}}"

  # =============================================================================
  # LOKI - LOGS DATA SOURCE
  # =============================================================================
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60
      derivedFields:
        - name: "TraceID"
          matcherRegex: "traceID=(\\w+)"
          url: "http://localhost:16686/trace/$${__value.raw}"
          datasourceUid: "jaeger"
        - name: "UserID"
          matcherRegex: "userID=(\\w+)"
          url: "/explore?orgId=1&left=[\"now-1h\",\"now\",\"Loki\",{\"expr\":\"{job=\\\"monomi-backend\\\"} |= \\\"$${__value.raw}\\\"\"}]"
        - name: "InvoiceID"
          matcherRegex: "invoiceID=(\\w+)"
          url: "/d/monomi-business/monomi-business-dashboard?var-invoice_id=$${__value.raw}"

  # =============================================================================
  # ALERTMANAGER - ALERTS DATA SOURCE
  # =============================================================================
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    uid: "alertmanager"
    editable: true
    jsonData:
      implementation: "prometheus"
      handleGrafanaManagedAlerts: true

  # =============================================================================
  # TESTDATA - FOR DASHBOARD DEVELOPMENT
  # =============================================================================
  - name: TestData
    type: testdata
    uid: "testdata"
    editable: false
    jsonData: {}

# =============================================================================
# INDONESIAN BUSINESS CONTEXT ANNOTATIONS
# =============================================================================
# This configuration supports:
# - Indonesian Rupiah (IDR) currency formatting
# - Materai compliance monitoring (5M IDR threshold)
# - Indonesian business hours (WIB timezone)
# - Quotation-to-Invoice workflow tracking
# - Multi-language support (Bahasa Indonesia)