/* GENERATED by frontend/scripts/guides/capture.mjs - do not edit by hand. */
export const guideImageManifest: Partial<Record<string, { w: number; h: number }>> = {
  "akuntansi-dasar/bagan-akun": {
    "w": 1440,
    "h": 860
  },
  "akuntansi-dasar/jurnal": {
    "w": 1440,
    "h": 860
  },
  "akuntansi-dasar/jurnal-baris": {
    "w": 1440,
    "h": 860
  },
  "akuntansi-dasar/jurnal-baru": {
    "w": 1440,
    "h": 860
  },
  "akuntansi-dasar/kas-bank": {
    "w": 1440,
    "h": 860
  },
  "akuntansi-dasar/laba-rugi": {
    "w": 1440,
    "h": 860
  },
  "akuntansi-dasar/neraca": {
    "w": 1440,
    "h": 860
  },
  "aset-penyusutan/akuisisi": {
    "w": 1280,
    "h": 820
  },
  "aset-penyusutan/daftar": {
    "w": 1280,
    "h": 820
  },
  "aset-penyusutan/detail": {
    "w": 1280,
    "h": 820
  },
  "aset-penyusutan/identitas": {
    "w": 1280,
    "h": 820
  },
  "aset-penyusutan/penyusutan-form": {
    "w": 1280,
    "h": 820
  },
  "aset-penyusutan/proses": {
    "w": 1280,
    "h": 820
  },
  "call-sheet/buat": {
    "w": 1280,
    "h": 820
  },
  "call-sheet/daftar": {
    "w": 1280,
    "h": 820
  },
  "call-sheet/editor": {
    "w": 1280,
    "h": 820
  },
  "call-sheet/info": {
    "w": 1280,
    "h": 820
  },
  "call-sheet/kru": {
    "w": 1280,
    "h": 820
  },
  "call-sheet/lokasi": {
    "w": 1280,
    "h": 820
  },
  "call-sheet/siap": {
    "w": 1280,
    "h": 820
  },
  "crm-leads-whatsapp/biaya-iklan": {
    "w": 1440,
    "h": 900
  },
  "crm-leads-whatsapp/daftar": {
    "w": 1440,
    "h": 900
  },
  "crm-leads-whatsapp/dasbor": {
    "w": 1440,
    "h": 900
  },
  "crm-leads-whatsapp/hasil": {
    "w": 1440,
    "h": 900
  },
  "crm-leads-whatsapp/kampanye": {
    "w": 1440,
    "h": 900
  },
  "crm-leads-whatsapp/konversi": {
    "w": 1440,
    "h": 900
  },
  "crm-leads-whatsapp/papan": {
    "w": 1440,
    "h": 900
  },
  "crm-leads-whatsapp/pesan-iklan": {
    "w": 1440,
    "h": 900
  },
  "crm-leads-whatsapp/pindah-tahap": {
    "w": 1440,
    "h": 900
  },
  "crm-leads-whatsapp/tambah-lead": {
    "w": 1440,
    "h": 900
  },
  "crm-leads-whatsapp/tindak-lanjut": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/balas": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/balasan-cepat": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/buka-inbox": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/dari-hp": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/di-hp": {
    "w": 780,
    "h": 1688
  },
  "crm-whatsapp-inbox/filter": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/jendela-24-jam": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/lead-otomatis": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/pengaturan": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/tab-lead": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/template": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-inbox/tetapkan": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-setup/aturan-keselamatan": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-setup/belum-lengkap": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-setup/capi": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-setup/hubungkan": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-setup/kartu-status": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-setup/lokasi-token": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-setup/mati": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-setup/tidak-valid": {
    "w": 1440,
    "h": 900
  },
  "crm-whatsapp-setup/webhook": {
    "w": 1440,
    "h": 900
  },
  "dashboard-navigasi/bahasa": {
    "w": 1280,
    "h": 820
  },
  "dashboard-navigasi/bahasa-en": {
    "w": 1280,
    "h": 820
  },
  "dashboard-navigasi/dashboard": {
    "w": 1280,
    "h": 820
  },
  "dashboard-navigasi/menu": {
    "w": 1280,
    "h": 820
  },
  "dashboard-navigasi/palet": {
    "w": 1280,
    "h": 820
  },
  "deck-klien/daftar": {
    "w": 780,
    "h": 1688
  },
  "deck-klien/komentar": {
    "w": 780,
    "h": 1688
  },
  "deck-klien/slide": {
    "w": 780,
    "h": 1688
  },
  "deck-presentasi/bagikan": {
    "w": 1920,
    "h": 960
  },
  "deck-presentasi/bagikan-tombol": {
    "w": 1920,
    "h": 960
  },
  "deck-presentasi/buat": {
    "w": 1920,
    "h": 960
  },
  "deck-presentasi/daftar": {
    "w": 1920,
    "h": 960
  },
  "deck-presentasi/editor": {
    "w": 1920,
    "h": 960
  },
  "deck-presentasi/ekspor": {
    "w": 1920,
    "h": 960
  },
  "deck-presentasi/slide-baru": {
    "w": 1920,
    "h": 960
  },
  "deck-presentasi/teks": {
    "w": 1920,
    "h": 960
  },
  "deck-presentasi/teks-menu": {
    "w": 1920,
    "h": 960
  },
  "gaji/draft": {
    "w": 1280,
    "h": 820
  },
  "gaji/karyawan": {
    "w": 1280,
    "h": 820
  },
  "gaji/karyawan-baru": {
    "w": 1280,
    "h": 820
  },
  "gaji/pembayaran": {
    "w": 1280,
    "h": 820
  },
  "invoice/daftar": {
    "w": 1280,
    "h": 820
  },
  "invoice/dari-penawaran": {
    "w": 1280,
    "h": 820
  },
  "invoice/kirim": {
    "w": 1280,
    "h": 820
  },
  "invoice/materai": {
    "w": 1280,
    "h": 820
  },
  "invoice/materai-tempel": {
    "w": 1280,
    "h": 820
  },
  "invoice/pdf": {
    "w": 1280,
    "h": 820
  },
  "invoice/status": {
    "w": 1280,
    "h": 820
  },
  "jadwal-syuting/buat": {
    "w": 1280,
    "h": 820
  },
  "jadwal-syuting/daftar": {
    "w": 1280,
    "h": 820
  },
  "jadwal-syuting/hari": {
    "w": 1280,
    "h": 820
  },
  "jadwal-syuting/impor-dialog": {
    "w": 1280,
    "h": 820
  },
  "jadwal-syuting/impor-menu": {
    "w": 1280,
    "h": 820
  },
  "jadwal-syuting/otomatis": {
    "w": 1280,
    "h": 820
  },
  "jadwal-syuting/otomatis-sebelum": {
    "w": 1280,
    "h": 820
  },
  "jadwal-syuting/strip": {
    "w": 1280,
    "h": 820
  },
  "klien-baru/daftar": {
    "w": 1280,
    "h": 820
  },
  "klien-baru/identitas": {
    "w": 1280,
    "h": 820
  },
  "klien-baru/kontak": {
    "w": 1280,
    "h": 820
  },
  "klien-baru/profil": {
    "w": 1280,
    "h": 820
  },
  "klien-baru/riwayat": {
    "w": 1280,
    "h": 820
  },
  "klien-baru/riwayat-invoice": {
    "w": 1280,
    "h": 820
  },
  "klien-baru/ubah": {
    "w": 1280,
    "h": 820
  },
  "kolaborasi-media/folder": {
    "w": 1280,
    "h": 900
  },
  "kolaborasi-media/pilih-hp": {
    "w": 780,
    "h": 1688
  },
  "kolaborasi-media/pilih-unduh": {
    "w": 1280,
    "h": 900
  },
  "kolaborasi-media/proyek-baru": {
    "w": 1280,
    "h": 900
  },
  "kolaborasi-media/rating": {
    "w": 1280,
    "h": 900
  },
  "kolaborasi-media/tautan": {
    "w": 1280,
    "h": 900
  },
  "kolaborasi-media/unggah": {
    "w": 1280,
    "h": 900
  },
  "konten-monomi/klien-monomi": {
    "w": 1280,
    "h": 900
  },
  "konten-monomi/planner-monomi": {
    "w": 1280,
    "h": 900
  },
  "konten-monomi/profil-instagram": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/angka-utama": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/bagian-data": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/daftar": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/grafik": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/identitas": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/kembali-draf": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/ketik-tabel": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/kirim": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/pratinjau-file": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/pratinjau-klien": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/salin": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/tayangkan": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/tempel-excel": {
    "w": 1280,
    "h": 900
  },
  "laporan-bulanan/unggah-file": {
    "w": 1280,
    "h": 900
  },
  "masuk-portal/beranda": {
    "w": 780,
    "h": 1688
  },
  "masuk-portal/email": {
    "w": 780,
    "h": 1688
  },
  "masuk-portal/kode": {
    "w": 780,
    "h": 1688
  },
  "masuk-portal/pilih-klien": {
    "w": 780,
    "h": 1688
  },
  "media-downloader/kualitas": {
    "w": 1280,
    "h": 820
  },
  "media-downloader/tautan": {
    "w": 1280,
    "h": 820
  },
  "media-downloader/unduh": {
    "w": 1280,
    "h": 820
  },
  "media-klien/daftar": {
    "w": 780,
    "h": 1688
  },
  "media-klien/galeri": {
    "w": 780,
    "h": 1688
  },
  "media-klien/lightbox": {
    "w": 780,
    "h": 1688
  },
  "media-klien/rating": {
    "w": 780,
    "h": 1688
  },
  "membaca-laporan/daftar": {
    "w": 780,
    "h": 1688
  },
  "membaca-laporan/data": {
    "w": 780,
    "h": 1688
  },
  "membaca-laporan/grafik": {
    "w": 780,
    "h": 1688
  },
  "membaca-laporan/ringkasan": {
    "w": 780,
    "h": 1688
  },
  "pengeluaran/daftar": {
    "w": 1280,
    "h": 820
  },
  "pengeluaran/detail": {
    "w": 1280,
    "h": 820
  },
  "pengeluaran/jurnal": {
    "w": 1280,
    "h": 820
  },
  "pengeluaran/kategori": {
    "w": 1280,
    "h": 820
  },
  "pengeluaran/pajak": {
    "w": 1280,
    "h": 820
  },
  "pengeluaran/proyek": {
    "w": 1280,
    "h": 820
  },
  "pengeluaran/tersimpan": {
    "w": 1280,
    "h": 820
  },
  "pengeluaran/vendor": {
    "w": 1280,
    "h": 820
  },
  "pengguna-peran/daftar": {
    "w": 1280,
    "h": 820
  },
  "pengguna-peran/hasil": {
    "w": 1280,
    "h": 820
  },
  "pengguna-peran/peran": {
    "w": 1280,
    "h": 820
  },
  "pengguna-peran/sandi": {
    "w": 1280,
    "h": 820
  },
  "penjualan/baru": {
    "w": 1440,
    "h": 860
  },
  "penjualan/laporan": {
    "w": 1440,
    "h": 860
  },
  "penjualan/lunas": {
    "w": 1440,
    "h": 860
  },
  "perencana-konten/aksi-massal": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/bagikan": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/buat-konten": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/detail-aksi": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/highlights": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/kalender": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/media-jadwal": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/pilih-klien": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/pratinjau-ig": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/pratinjau-tiktok": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/seret": {
    "w": 1280,
    "h": 900
  },
  "perencana-konten/terbitkan": {
    "w": 1280,
    "h": 900
  },
  "pintasan-keyboard/bantuan": {
    "w": 1280,
    "h": 800
  },
  "pintasan-keyboard/deck": {
    "w": 1600,
    "h": 900
  },
  "pintasan-keyboard/media": {
    "w": 1280,
    "h": 800
  },
  "pintasan-keyboard/presentasi": {
    "w": 1600,
    "h": 900
  },
  "pintasan-klien/bantuan": {
    "w": 1280,
    "h": 800
  },
  "pintasan-klien/foto": {
    "w": 1280,
    "h": 800
  },
  "piutang-pembayaran/form": {
    "w": 1280,
    "h": 820
  },
  "piutang-pembayaran/hasil": {
    "w": 1280,
    "h": 820
  },
  "piutang-pembayaran/jatuh-tempo": {
    "w": 1280,
    "h": 820
  },
  "piutang-pembayaran/piutang": {
    "w": 1440,
    "h": 860
  },
  "piutang-pembayaran/tombol": {
    "w": 1280,
    "h": 820
  },
  "portal-klien/aktif-undang": {
    "w": 1280,
    "h": 900
  },
  "portal-klien/dilihat-klien": {
    "w": 1280,
    "h": 800
  },
  "portal-klien/kartu": {
    "w": 1280,
    "h": 900
  },
  "portal-klien/tambah-kontak": {
    "w": 1280,
    "h": 900
  },
  "production-hub/buka": {
    "w": 1280,
    "h": 820
  },
  "production-hub/isi": {
    "w": 1280,
    "h": 820
  },
  "production-hub/tamu": {
    "w": 1280,
    "h": 820
  },
  "production-hub/tautan": {
    "w": 1280,
    "h": 820
  },
  "proyek-baru/anggaran": {
    "w": 1280,
    "h": 820
  },
  "proyek-baru/daftar": {
    "w": 1280,
    "h": 820
  },
  "proyek-baru/detail": {
    "w": 1280,
    "h": 820
  },
  "proyek-baru/identitas": {
    "w": 1280,
    "h": 820
  },
  "proyek-baru/klien-jenis": {
    "w": 1280,
    "h": 820
  },
  "proyek-baru/production-hub": {
    "w": 1280,
    "h": 820
  },
  "proyek-baru/produk": {
    "w": 1280,
    "h": 820
  },
  "proyek-baru/status": {
    "w": 1280,
    "h": 820
  },
  "publikasi-otomatis/gagal": {
    "w": 1440,
    "h": 1100
  },
  "publikasi-otomatis/koneksi": {
    "w": 1440,
    "h": 1100
  },
  "publikasi-otomatis/nyalakan": {
    "w": 1440,
    "h": 1100
  },
  "publikasi-otomatis/status": {
    "w": 1440,
    "h": 1100
  },
  "publikasi-otomatis/syarat": {
    "w": 1440,
    "h": 1100
  },
  "publikasi-otomatis/terbit": {
    "w": 1440,
    "h": 1100
  },
  "publikasi-otomatis/terbitkan-sekarang": {
    "w": 1440,
    "h": 1100
  },
  "quotation/daftar": {
    "w": 1280,
    "h": 820
  },
  "quotation/disetujui": {
    "w": 1280,
    "h": 820
  },
  "quotation/item": {
    "w": 1280,
    "h": 820
  },
  "quotation/ketentuan": {
    "w": 1280,
    "h": 820
  },
  "quotation/kirim": {
    "w": 1280,
    "h": 820
  },
  "quotation/klien-proyek": {
    "w": 1280,
    "h": 820
  },
  "quotation/ppn": {
    "w": 1280,
    "h": 820
  },
  "quotation/revisi": {
    "w": 1280,
    "h": 820
  },
  "quotation/setujui": {
    "w": 1280,
    "h": 820
  },
  "rencana-konten-klien/ponsel": {
    "w": 780,
    "h": 1688
  },
  "rencana-konten-klien/rencana": {
    "w": 780,
    "h": 1688
  },
  "shot-list/buat": {
    "w": 1280,
    "h": 820
  },
  "shot-list/daftar": {
    "w": 1280,
    "h": 820
  },
  "shot-list/editor": {
    "w": 1280,
    "h": 820
  },
  "shot-list/pdf": {
    "w": 1280,
    "h": 820
  },
  "shot-list/shot": {
    "w": 1280,
    "h": 820
  },
  "shot-list/urutan": {
    "w": 1280,
    "h": 820
  },
  "vendor-pembelian/bank": {
    "w": 1280,
    "h": 820
  },
  "vendor-pembelian/daftar": {
    "w": 1280,
    "h": 820
  },
  "vendor-pembelian/hutang": {
    "w": 1280,
    "h": 820
  },
  "vendor-pembelian/identitas": {
    "w": 1280,
    "h": 820
  },
  "vendor-pembelian/pajak": {
    "w": 1280,
    "h": 820
  },
  "vendor-pembelian/pembelian": {
    "w": 1280,
    "h": 820
  }
};
