/* GENERATED by frontend/scripts/guides/build-videos.mjs - do not edit by hand.
 * File names are relative to the video base URL (VITE_GUIDE_VIDEO_BASE, default
 * https://media.monomiagency.com/public-guides) and carry a content hash. */
export interface GuideVideoChapter {
  /** Step id (see guides data). */
  step: string;
  /** Seconds into the video. */
  start: number;
  end: number;
}

export interface GuideVideo {
  mp4: string;
  poster: string;
  /** Captions per UI language. */
  vtt: { id: string; en: string };
  /** Chapter tracks (one cue per step) per UI language. */
  chaptersVtt: { id: string; en: string };
  chapters: GuideVideoChapter[];
  /** Pixel size of the picture, so the player box never jumps. */
  w: number;
  h: number;
  durationSec: number;
  /** Hash of the MP4: changes whenever the video does. */
  version: string;
}

export const guideVideoManifest: Partial<Record<string, GuideVideo>> = {
  "akuntansi-dasar": {
    "mp4": "akuntansi-dasar.b374952d.mp4",
    "poster": "akuntansi-dasar.b374952d.webp",
    "vtt": {
      "id": "akuntansi-dasar.3f5cc994.id.vtt",
      "en": "akuntansi-dasar.3ebc7fc5.en.vtt"
    },
    "chaptersVtt": {
      "id": "akuntansi-dasar.59dd5470.chapters.id.vtt",
      "en": "akuntansi-dasar.a068f2fb.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "jurnal",
        "start": 0,
        "end": 9.22
      },
      {
        "step": "jurnal-baru",
        "start": 9.22,
        "end": 22.43
      },
      {
        "step": "jurnal-baris",
        "start": 22.43,
        "end": 43.38
      },
      {
        "step": "kas-bank",
        "start": 43.38,
        "end": 58.8
      },
      {
        "step": "laba-rugi",
        "start": 58.8,
        "end": 68.94
      },
      {
        "step": "neraca",
        "start": 68.94,
        "end": 81.09
      },
      {
        "step": "bagan-akun",
        "start": 81.09,
        "end": 93.47
      }
    ],
    "w": 1280,
    "h": 764,
    "durationSec": 93.5,
    "version": "b374952d"
  },
  "aset-penyusutan": {
    "mp4": "aset-penyusutan.deab8184.mp4",
    "poster": "aset-penyusutan.deab8184.webp",
    "vtt": {
      "id": "aset-penyusutan.10447876.id.vtt",
      "en": "aset-penyusutan.b73261a4.en.vtt"
    },
    "chaptersVtt": {
      "id": "aset-penyusutan.b0ca41d3.chapters.id.vtt",
      "en": "aset-penyusutan.ce0ac998.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.41
      },
      {
        "step": "identitas",
        "start": 9.41,
        "end": 29.4
      },
      {
        "step": "akuisisi",
        "start": 29.4,
        "end": 39.47
      },
      {
        "step": "penyusutan-form",
        "start": 39.47,
        "end": 50.77
      },
      {
        "step": "detail",
        "start": 50.77,
        "end": 63.22
      },
      {
        "step": "proses",
        "start": 63.22,
        "end": 75.67
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 75.7,
    "version": "deab8184"
  },
  "call-sheet": {
    "mp4": "call-sheet.7601fc91.mp4",
    "poster": "call-sheet.7601fc91.webp",
    "vtt": {
      "id": "call-sheet.8fb71437.id.vtt",
      "en": "call-sheet.965e2a52.en.vtt"
    },
    "chaptersVtt": {
      "id": "call-sheet.c652d334.chapters.id.vtt",
      "en": "call-sheet.7b3d5c69.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.28
      },
      {
        "step": "buat",
        "start": 9.28,
        "end": 23.52
      },
      {
        "step": "info",
        "start": 23.52,
        "end": 39.33
      },
      {
        "step": "lokasi",
        "start": 39.33,
        "end": 52.33
      },
      {
        "step": "kru",
        "start": 52.33,
        "end": 66.57
      },
      {
        "step": "siap",
        "start": 66.57,
        "end": 79.43
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 79.4,
    "version": "7601fc91"
  },
  "crm-leads-whatsapp": {
    "mp4": "crm-leads-whatsapp.7211b213.mp4",
    "poster": "crm-leads-whatsapp.7211b213.webp",
    "vtt": {
      "id": "crm-leads-whatsapp.3625f627.id.vtt",
      "en": "crm-leads-whatsapp.7e60c2cf.en.vtt"
    },
    "chaptersVtt": {
      "id": "crm-leads-whatsapp.21d289a1.chapters.id.vtt",
      "en": "crm-leads-whatsapp.a70ee487.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "kampanye",
        "start": 0,
        "end": 11.44
      },
      {
        "step": "pesan-iklan",
        "start": 11.44,
        "end": 20.86
      },
      {
        "step": "link-iklan-website",
        "start": 20.86,
        "end": 30.75
      },
      {
        "step": "biaya-iklan",
        "start": 30.75,
        "end": 41.9
      },
      {
        "step": "tambah-lead",
        "start": 41.9,
        "end": 57.72
      },
      {
        "step": "kode-chat",
        "start": 57.72,
        "end": 69.78
      },
      {
        "step": "lead-menunggu-wa",
        "start": 69.78,
        "end": 83.61
      },
      {
        "step": "papan",
        "start": 83.61,
        "end": 96.6
      },
      {
        "step": "daftar",
        "start": 96.6,
        "end": 105.42
      },
      {
        "step": "tindak-lanjut",
        "start": 105.42,
        "end": 116.33
      },
      {
        "step": "pindah-tahap",
        "start": 116.33,
        "end": 128.03
      },
      {
        "step": "konversi",
        "start": 128.03,
        "end": 139.32
      },
      {
        "step": "hasil",
        "start": 139.32,
        "end": 152.24
      },
      {
        "step": "dasbor",
        "start": 152.24,
        "end": 166.43
      }
    ],
    "w": 1280,
    "h": 800,
    "durationSec": 166.4,
    "version": "7211b213"
  },
  "crm-whatsapp-inbox": {
    "mp4": "crm-whatsapp-inbox.daa4e56c.mp4",
    "poster": "crm-whatsapp-inbox.daa4e56c.webp",
    "vtt": {
      "id": "crm-whatsapp-inbox.d257aa16.id.vtt",
      "en": "crm-whatsapp-inbox.97ebceb2.en.vtt"
    },
    "chaptersVtt": {
      "id": "crm-whatsapp-inbox.73d5bb83.chapters.id.vtt",
      "en": "crm-whatsapp-inbox.80285dbc.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "buka-inbox",
        "start": 0,
        "end": 9.31
      },
      {
        "step": "filter",
        "start": 9.31,
        "end": 16.47
      },
      {
        "step": "lead-otomatis",
        "start": 16.47,
        "end": 27.77
      },
      {
        "step": "balas",
        "start": 27.81,
        "end": 43.23
      },
      {
        "step": "balasan-cepat",
        "start": 43.27,
        "end": 55.15
      },
      {
        "step": "dari-hp",
        "start": 55.19,
        "end": 64.49
      },
      {
        "step": "jendela-24-jam",
        "start": 64.49,
        "end": 76.81
      },
      {
        "step": "template",
        "start": 76.81,
        "end": 89.13
      },
      {
        "step": "tetapkan",
        "start": 89.13,
        "end": 103.51
      },
      {
        "step": "tab-lead",
        "start": 103.51,
        "end": 117.75
      },
      {
        "step": "di-hp",
        "start": 117.79,
        "end": 127.03
      },
      {
        "step": "pengaturan",
        "start": 127.07,
        "end": 140.6
      }
    ],
    "w": 1280,
    "h": 800,
    "durationSec": 140.6,
    "version": "daa4e56c"
  },
  "crm-whatsapp-setup": {
    "mp4": "crm-whatsapp-setup.a1f881bc.mp4",
    "poster": "crm-whatsapp-setup.a1f881bc.webp",
    "vtt": {
      "id": "crm-whatsapp-setup.d9946e21.id.vtt",
      "en": "crm-whatsapp-setup.1b5bb818.en.vtt"
    },
    "chaptersVtt": {
      "id": "crm-whatsapp-setup.7e7116a3.chapters.id.vtt",
      "en": "crm-whatsapp-setup.389ad04d.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "aturan-keselamatan",
        "start": 0,
        "end": 10.51
      },
      {
        "step": "lokasi-token",
        "start": 10.55,
        "end": 19.85
      },
      {
        "step": "kartu-status",
        "start": 19.89,
        "end": 28.71
      },
      {
        "step": "webhook",
        "start": 28.75,
        "end": 40.82
      },
      {
        "step": "capi",
        "start": 40.82,
        "end": 49.03
      },
      {
        "step": "hubungkan",
        "start": 49.03,
        "end": 59
      },
      {
        "step": "pelacakan-landing-page",
        "start": 59,
        "end": 68.94
      },
      {
        "step": "sinkronisasi-meta-ads",
        "start": 68.94,
        "end": 78.83
      }
    ],
    "w": 1280,
    "h": 800,
    "durationSec": 78.8,
    "version": "a1f881bc"
  },
  "dashboard-navigasi": {
    "mp4": "dashboard-navigasi.ad84b00a.mp4",
    "poster": "dashboard-navigasi.ad84b00a.webp",
    "vtt": {
      "id": "dashboard-navigasi.13e0a782.id.vtt",
      "en": "dashboard-navigasi.85172f6c.en.vtt"
    },
    "chaptersVtt": {
      "id": "dashboard-navigasi.d1896c9e.chapters.id.vtt",
      "en": "dashboard-navigasi.c8864d5f.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "dashboard",
        "start": 0,
        "end": 9.2
      },
      {
        "step": "menu",
        "start": 9.2,
        "end": 21.45
      },
      {
        "step": "palet",
        "start": 21.45,
        "end": 33.78
      },
      {
        "step": "bahasa",
        "start": 33.78,
        "end": 44.2
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 44.2,
    "version": "ad84b00a"
  },
  "deck-klien": {
    "mp4": "deck-klien.f55cddd1.mp4",
    "poster": "deck-klien.f55cddd1.webp",
    "vtt": {
      "id": "deck-klien.15ecd369.id.vtt",
      "en": "deck-klien.304de6d0.en.vtt"
    },
    "chaptersVtt": {
      "id": "deck-klien.5be95f77.chapters.id.vtt",
      "en": "deck-klien.9db1a24a.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 6.34
      },
      {
        "step": "slide",
        "start": 6.34,
        "end": 14.17
      },
      {
        "step": "komentar",
        "start": 14.17,
        "end": 23.57
      }
    ],
    "w": 540,
    "h": 1168,
    "durationSec": 23.6,
    "version": "f55cddd1"
  },
  "deck-presentasi": {
    "mp4": "deck-presentasi.5017d691.mp4",
    "poster": "deck-presentasi.5017d691.webp",
    "vtt": {
      "id": "deck-presentasi.79b3aba5.id.vtt",
      "en": "deck-presentasi.c47db5d2.en.vtt"
    },
    "chaptersVtt": {
      "id": "deck-presentasi.4ce44305.chapters.id.vtt",
      "en": "deck-presentasi.84c612c4.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.42
      },
      {
        "step": "buat",
        "start": 9.42,
        "end": 22.79
      },
      {
        "step": "editor",
        "start": 22.79,
        "end": 31.01
      },
      {
        "step": "teks-menu",
        "start": 31.01,
        "end": 41.15
      },
      {
        "step": "teks",
        "start": 41.15,
        "end": 53.31
      },
      {
        "step": "slide-baru",
        "start": 53.31,
        "end": 65.47
      },
      {
        "step": "bagikan-tombol",
        "start": 65.47,
        "end": 74.85
      },
      {
        "step": "bagikan",
        "start": 74.85,
        "end": 86.14
      },
      {
        "step": "ekspor",
        "start": 86.14,
        "end": 97.07
      }
    ],
    "w": 1280,
    "h": 640,
    "durationSec": 97.1,
    "version": "5017d691"
  },
  "gaji": {
    "mp4": "gaji.52cff713.mp4",
    "poster": "gaji.52cff713.webp",
    "vtt": {
      "id": "gaji.ea2c3a89.id.vtt",
      "en": "gaji.612170e5.en.vtt"
    },
    "chaptersVtt": {
      "id": "gaji.6e4021cf.chapters.id.vtt",
      "en": "gaji.a4343a83.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "karyawan",
        "start": 0,
        "end": 9.53
      },
      {
        "step": "karyawan-baru",
        "start": 9.53,
        "end": 31.24
      },
      {
        "step": "pembayaran",
        "start": 31.24,
        "end": 48.88
      },
      {
        "step": "draft",
        "start": 48.88,
        "end": 63.07
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 63.1,
    "version": "52cff713"
  },
  "invoice": {
    "mp4": "invoice.8d19f76d.mp4",
    "poster": "invoice.8d19f76d.webp",
    "vtt": {
      "id": "invoice.84ba3998.id.vtt",
      "en": "invoice.759fd867.en.vtt"
    },
    "chaptersVtt": {
      "id": "invoice.31357630.chapters.id.vtt",
      "en": "invoice.247118c7.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.31
      },
      {
        "step": "status",
        "start": 9.31,
        "end": 20.65
      },
      {
        "step": "dari-penawaran",
        "start": 20.65,
        "end": 33.09
      },
      {
        "step": "materai",
        "start": 33.09,
        "end": 42.26
      },
      {
        "step": "materai-tempel",
        "start": 42.26,
        "end": 54.71
      },
      {
        "step": "pdf",
        "start": 54.71,
        "end": 66.45
      },
      {
        "step": "kirim",
        "start": 66.45,
        "end": 78.57
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 78.6,
    "version": "8d19f76d"
  },
  "jadwal-syuting": {
    "mp4": "jadwal-syuting.88c8f336.mp4",
    "poster": "jadwal-syuting.88c8f336.webp",
    "vtt": {
      "id": "jadwal-syuting.2d15453d.id.vtt",
      "en": "jadwal-syuting.fd805fe3.en.vtt"
    },
    "chaptersVtt": {
      "id": "jadwal-syuting.c1f4b9f8.chapters.id.vtt",
      "en": "jadwal-syuting.a682f066.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 8.23
      },
      {
        "step": "buat",
        "start": 8.23,
        "end": 23.88
      },
      {
        "step": "hari",
        "start": 23.88,
        "end": 37.14
      },
      {
        "step": "impor-menu",
        "start": 37.14,
        "end": 48.01
      },
      {
        "step": "impor-dialog",
        "start": 48.01,
        "end": 59.69
      },
      {
        "step": "strip",
        "start": 59.69,
        "end": 68.06
      },
      {
        "step": "otomatis",
        "start": 68.06,
        "end": 78.2
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 78.2,
    "version": "88c8f336"
  },
  "klien-baru": {
    "mp4": "klien-baru.ee81973a.mp4",
    "poster": "klien-baru.ee81973a.webp",
    "vtt": {
      "id": "klien-baru.44568692.id.vtt",
      "en": "klien-baru.73fb1756.en.vtt"
    },
    "chaptersVtt": {
      "id": "klien-baru.7a57306f.chapters.id.vtt",
      "en": "klien-baru.85644c2d.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.26
      },
      {
        "step": "identitas",
        "start": 9.26,
        "end": 26.25
      },
      {
        "step": "kontak",
        "start": 26.25,
        "end": 46.61
      },
      {
        "step": "profil",
        "start": 46.61,
        "end": 58.35
      },
      {
        "step": "riwayat",
        "start": 58.35,
        "end": 67.72
      },
      {
        "step": "riwayat-invoice",
        "start": 67.72,
        "end": 77.78
      },
      {
        "step": "ubah",
        "start": 77.78,
        "end": 89.53
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 89.5,
    "version": "ee81973a"
  },
  "kolaborasi-media": {
    "mp4": "kolaborasi-media.e8c4510c.mp4",
    "poster": "kolaborasi-media.e8c4510c.webp",
    "vtt": {
      "id": "kolaborasi-media.3f659c6a.id.vtt",
      "en": "kolaborasi-media.0d45f07f.en.vtt"
    },
    "chaptersVtt": {
      "id": "kolaborasi-media.f205e838.chapters.id.vtt",
      "en": "kolaborasi-media.1bf853d8.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "proyek-baru",
        "start": 0,
        "end": 9.21
      },
      {
        "step": "unggah",
        "start": 9.21,
        "end": 18.19
      },
      {
        "step": "folder",
        "start": 18.19,
        "end": 28.26
      },
      {
        "step": "pilih-unduh",
        "start": 28.26,
        "end": 40.05
      },
      {
        "step": "pilih-hp",
        "start": 40.09,
        "end": 51.41
      },
      {
        "step": "rating",
        "start": 51.45,
        "end": 67.67
      },
      {
        "step": "tautan",
        "start": 67.67,
        "end": 79.4
      }
    ],
    "w": 1280,
    "h": 900,
    "durationSec": 79.4,
    "version": "e8c4510c"
  },
  "konten-monomi": {
    "mp4": "konten-monomi.1d3f64eb.mp4",
    "poster": "konten-monomi.1d3f64eb.webp",
    "vtt": {
      "id": "konten-monomi.8b3a3ac3.id.vtt",
      "en": "konten-monomi.02004595.en.vtt"
    },
    "chaptersVtt": {
      "id": "konten-monomi.6f360132.chapters.id.vtt",
      "en": "konten-monomi.4ba64d97.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "klien-monomi",
        "start": 0,
        "end": 8.63
      },
      {
        "step": "profil-instagram",
        "start": 8.63,
        "end": 22.07
      },
      {
        "step": "planner-monomi",
        "start": 22.07,
        "end": 35.8
      }
    ],
    "w": 1280,
    "h": 900,
    "durationSec": 35.8,
    "version": "1d3f64eb"
  },
  "laporan-bulanan": {
    "mp4": "laporan-bulanan.44bd4f86.mp4",
    "poster": "laporan-bulanan.44bd4f86.webp",
    "vtt": {
      "id": "laporan-bulanan.500b61cf.id.vtt",
      "en": "laporan-bulanan.8e2e5633.en.vtt"
    },
    "chaptersVtt": {
      "id": "laporan-bulanan.904221b4.chapters.id.vtt",
      "en": "laporan-bulanan.30e9604e.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.3
      },
      {
        "step": "identitas",
        "start": 9.3,
        "end": 24.78
      },
      {
        "step": "bagian-data",
        "start": 24.78,
        "end": 37.27
      },
      {
        "step": "unggah-file",
        "start": 37.27,
        "end": 47.03
      },
      {
        "step": "pratinjau-file",
        "start": 47.03,
        "end": 57.82
      },
      {
        "step": "ketik-tabel",
        "start": 57.82,
        "end": 81.39
      },
      {
        "step": "tempel-excel",
        "start": 81.39,
        "end": 92.69
      },
      {
        "step": "angka-utama",
        "start": 92.69,
        "end": 105.52
      },
      {
        "step": "grafik",
        "start": 105.52,
        "end": 115.3
      },
      {
        "step": "pratinjau-klien",
        "start": 115.3,
        "end": 126.59
      },
      {
        "step": "tayangkan",
        "start": 126.59,
        "end": 139.58
      },
      {
        "step": "kirim",
        "start": 139.58,
        "end": 150.89
      },
      {
        "step": "kembali-draf",
        "start": 150.89,
        "end": 161.5
      },
      {
        "step": "salin",
        "start": 161.5,
        "end": 175.27
      }
    ],
    "w": 1280,
    "h": 900,
    "durationSec": 175.3,
    "version": "44bd4f86"
  },
  "masuk-portal": {
    "mp4": "masuk-portal.b7d3e23f.mp4",
    "poster": "masuk-portal.b7d3e23f.webp",
    "vtt": {
      "id": "masuk-portal.1d97dd57.id.vtt",
      "en": "masuk-portal.603740a3.en.vtt"
    },
    "chaptersVtt": {
      "id": "masuk-portal.53afbf3b.chapters.id.vtt",
      "en": "masuk-portal.7395d825.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "email",
        "start": 0,
        "end": 7.38
      },
      {
        "step": "kode",
        "start": 7.38,
        "end": 17.89
      },
      {
        "step": "pilih-klien",
        "start": 17.89,
        "end": 24.57
      },
      {
        "step": "beranda",
        "start": 24.57,
        "end": 34.77
      }
    ],
    "w": 540,
    "h": 1168,
    "durationSec": 34.8,
    "version": "b7d3e23f"
  },
  "media-downloader": {
    "mp4": "media-downloader.0edc8ac2.mp4",
    "poster": "media-downloader.0edc8ac2.webp",
    "vtt": {
      "id": "media-downloader.a19fd3d6.id.vtt",
      "en": "media-downloader.46319e34.en.vtt"
    },
    "chaptersVtt": {
      "id": "media-downloader.33acc281.chapters.id.vtt",
      "en": "media-downloader.4e7008d7.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "tautan",
        "start": 0,
        "end": 13.23
      },
      {
        "step": "kualitas",
        "start": 13.23,
        "end": 22.21
      },
      {
        "step": "unduh",
        "start": 22.21,
        "end": 32.23
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 32.2,
    "version": "0edc8ac2"
  },
  "media-klien": {
    "mp4": "media-klien.aba90817.mp4",
    "poster": "media-klien.aba90817.webp",
    "vtt": {
      "id": "media-klien.baa75039.id.vtt",
      "en": "media-klien.21d6e7f0.en.vtt"
    },
    "chaptersVtt": {
      "id": "media-klien.35c47571.chapters.id.vtt",
      "en": "media-klien.f510f918.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 5.53
      },
      {
        "step": "galeri",
        "start": 5.53,
        "end": 15.19
      },
      {
        "step": "lightbox",
        "start": 15.19,
        "end": 25.33
      },
      {
        "step": "rating",
        "start": 25.33,
        "end": 34.77
      }
    ],
    "w": 540,
    "h": 1168,
    "durationSec": 34.8,
    "version": "aba90817"
  },
  "membaca-laporan": {
    "mp4": "membaca-laporan.9c37b25a.mp4",
    "poster": "membaca-laporan.9c37b25a.webp",
    "vtt": {
      "id": "membaca-laporan.c760ca52.id.vtt",
      "en": "membaca-laporan.7eda487e.en.vtt"
    },
    "chaptersVtt": {
      "id": "membaca-laporan.4bd075c7.chapters.id.vtt",
      "en": "membaca-laporan.5861aa20.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 7.09
      },
      {
        "step": "ringkasan",
        "start": 7.09,
        "end": 18.38
      },
      {
        "step": "grafik",
        "start": 18.38,
        "end": 28.52
      },
      {
        "step": "data",
        "start": 28.52,
        "end": 36.77
      }
    ],
    "w": 540,
    "h": 1168,
    "durationSec": 36.8,
    "version": "9c37b25a"
  },
  "pengeluaran": {
    "mp4": "pengeluaran.0d7baa83.mp4",
    "poster": "pengeluaran.0d7baa83.webp",
    "vtt": {
      "id": "pengeluaran.632ba200.id.vtt",
      "en": "pengeluaran.880af69b.en.vtt"
    },
    "chaptersVtt": {
      "id": "pengeluaran.a999c73b.chapters.id.vtt",
      "en": "pengeluaran.3e5372e5.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.33
      },
      {
        "step": "detail",
        "start": 9.33,
        "end": 28.25
      },
      {
        "step": "vendor",
        "start": 28.25,
        "end": 38.01
      },
      {
        "step": "pajak",
        "start": 38.01,
        "end": 50.45
      },
      {
        "step": "proyek",
        "start": 50.45,
        "end": 63.85
      },
      {
        "step": "tersimpan",
        "start": 63.85,
        "end": 76.43
      },
      {
        "step": "jurnal",
        "start": 76.43,
        "end": 89.26
      },
      {
        "step": "kategori",
        "start": 89.26,
        "end": 99.43
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 99.4,
    "version": "0d7baa83"
  },
  "pengguna-peran": {
    "mp4": "pengguna-peran.7deea84e.mp4",
    "poster": "pengguna-peran.7deea84e.webp",
    "vtt": {
      "id": "pengguna-peran.4ad297b2.id.vtt",
      "en": "pengguna-peran.98b91d86.en.vtt"
    },
    "chaptersVtt": {
      "id": "pengguna-peran.96970d67.chapters.id.vtt",
      "en": "pengguna-peran.06e03ee4.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.31
      },
      {
        "step": "peran",
        "start": 9.31,
        "end": 23.39
      },
      {
        "step": "sandi",
        "start": 23.39,
        "end": 36.22
      },
      {
        "step": "hasil",
        "start": 36.22,
        "end": 48.4
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 48.4,
    "version": "7deea84e"
  },
  "penjualan": {
    "mp4": "penjualan.7bb38808.mp4",
    "poster": "penjualan.7bb38808.webp",
    "vtt": {
      "id": "penjualan.d9db5a72.id.vtt",
      "en": "penjualan.f2c99187.en.vtt"
    },
    "chaptersVtt": {
      "id": "penjualan.ea9fbd5a.chapters.id.vtt",
      "en": "penjualan.7f9979ce.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "laporan",
        "start": 0,
        "end": 9.21
      },
      {
        "step": "lunas",
        "start": 9.21,
        "end": 20.49
      },
      {
        "step": "baru",
        "start": 20.49,
        "end": 45.13
      }
    ],
    "w": 1280,
    "h": 764,
    "durationSec": 45.1,
    "version": "7bb38808"
  },
  "perencana-konten": {
    "mp4": "perencana-konten.4cf26c33.mp4",
    "poster": "perencana-konten.4cf26c33.webp",
    "vtt": {
      "id": "perencana-konten.bb83410f.id.vtt",
      "en": "perencana-konten.43c35f4f.en.vtt"
    },
    "chaptersVtt": {
      "id": "perencana-konten.acb959f8.chapters.id.vtt",
      "en": "perencana-konten.526c764b.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "pilih-klien",
        "start": 0,
        "end": 8.61
      },
      {
        "step": "kalender",
        "start": 8.61,
        "end": 18.75
      },
      {
        "step": "buat-konten",
        "start": 18.75,
        "end": 31.11
      },
      {
        "step": "media-jadwal",
        "start": 31.11,
        "end": 43.8
      },
      {
        "step": "detail-aksi",
        "start": 43.8,
        "end": 56.24
      },
      {
        "step": "terbitkan",
        "start": 56.24,
        "end": 63.31
      },
      {
        "step": "seret",
        "start": 63.31,
        "end": 74.21
      },
      {
        "step": "aksi-massal",
        "start": 74.21,
        "end": 85.47
      },
      {
        "step": "pratinjau-ig",
        "start": 85.47,
        "end": 96.37
      },
      {
        "step": "highlights",
        "start": 96.37,
        "end": 106.12
      },
      {
        "step": "pratinjau-tiktok",
        "start": 106.12,
        "end": 116.65
      },
      {
        "step": "bagikan",
        "start": 116.65,
        "end": 129.53
      }
    ],
    "w": 1280,
    "h": 900,
    "durationSec": 129.5,
    "version": "4cf26c33"
  },
  "pintasan-keyboard": {
    "mp4": "pintasan-keyboard.552e4180.mp4",
    "poster": "pintasan-keyboard.552e4180.webp",
    "vtt": {
      "id": "pintasan-keyboard.c8846957.id.vtt",
      "en": "pintasan-keyboard.2aa11cac.en.vtt"
    },
    "chaptersVtt": {
      "id": "pintasan-keyboard.f319c869.chapters.id.vtt",
      "en": "pintasan-keyboard.21d99596.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "bantuan",
        "start": 0,
        "end": 10.77
      },
      {
        "step": "media",
        "start": 10.77,
        "end": 23.98
      },
      {
        "step": "deck",
        "start": 24.02,
        "end": 29.85
      },
      {
        "step": "presentasi",
        "start": 29.85,
        "end": 42.33
      }
    ],
    "w": 1280,
    "h": 800,
    "durationSec": 42.3,
    "version": "552e4180"
  },
  "pintasan-klien": {
    "mp4": "pintasan-klien.22e1c5b2.mp4",
    "poster": "pintasan-klien.22e1c5b2.webp",
    "vtt": {
      "id": "pintasan-klien.12dad02f.id.vtt",
      "en": "pintasan-klien.f1a965c9.en.vtt"
    },
    "chaptersVtt": {
      "id": "pintasan-klien.8dafbdfc.chapters.id.vtt",
      "en": "pintasan-klien.9e2f6523.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "bantuan",
        "start": 0,
        "end": 13.43
      },
      {
        "step": "foto",
        "start": 13.43,
        "end": 27.33
      }
    ],
    "w": 1280,
    "h": 800,
    "durationSec": 27.3,
    "version": "22e1c5b2"
  },
  "piutang-pembayaran": {
    "mp4": "piutang-pembayaran.dd74fd67.mp4",
    "poster": "piutang-pembayaran.dd74fd67.webp",
    "vtt": {
      "id": "piutang-pembayaran.7dd8aaed.id.vtt",
      "en": "piutang-pembayaran.81fd09c7.en.vtt"
    },
    "chaptersVtt": {
      "id": "piutang-pembayaran.22003efe.chapters.id.vtt",
      "en": "piutang-pembayaran.b944c10b.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "tombol",
        "start": 0,
        "end": 9.18
      },
      {
        "step": "form",
        "start": 9.18,
        "end": 21.33
      },
      {
        "step": "hasil",
        "start": 21.33,
        "end": 33.9
      },
      {
        "step": "jatuh-tempo",
        "start": 33.9,
        "end": 46.9
      },
      {
        "step": "piutang",
        "start": 46.94,
        "end": 56.17
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 56.2,
    "version": "dd74fd67"
  },
  "portal-klien": {
    "mp4": "portal-klien.a0827615.mp4",
    "poster": "portal-klien.a0827615.webp",
    "vtt": {
      "id": "portal-klien.a0ad5eb8.id.vtt",
      "en": "portal-klien.5060acc8.en.vtt"
    },
    "chaptersVtt": {
      "id": "portal-klien.51f56e86.chapters.id.vtt",
      "en": "portal-klien.2ea40469.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "kartu",
        "start": 0,
        "end": 10.2
      },
      {
        "step": "tambah-kontak",
        "start": 10.2,
        "end": 21.49
      },
      {
        "step": "aktif-undang",
        "start": 21.49,
        "end": 32.4
      },
      {
        "step": "dilihat-klien",
        "start": 32.44,
        "end": 43.8
      }
    ],
    "w": 1280,
    "h": 900,
    "durationSec": 43.8,
    "version": "a0827615"
  },
  "production-hub": {
    "mp4": "production-hub.5b4c1732.mp4",
    "poster": "production-hub.5b4c1732.webp",
    "vtt": {
      "id": "production-hub.da894188.id.vtt",
      "en": "production-hub.4acb2d70.en.vtt"
    },
    "chaptersVtt": {
      "id": "production-hub.703ef9db.chapters.id.vtt",
      "en": "production-hub.62875b19.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "buka",
        "start": 0,
        "end": 8.63
      },
      {
        "step": "isi",
        "start": 8.63,
        "end": 18
      },
      {
        "step": "tautan",
        "start": 18,
        "end": 28.14
      },
      {
        "step": "tamu",
        "start": 28.18,
        "end": 39.27
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 39.3,
    "version": "5b4c1732"
  },
  "proyek-baru": {
    "mp4": "proyek-baru.50acddac.mp4",
    "poster": "proyek-baru.50acddac.webp",
    "vtt": {
      "id": "proyek-baru.2a711cc3.id.vtt",
      "en": "proyek-baru.1044b4df.en.vtt"
    },
    "chaptersVtt": {
      "id": "proyek-baru.41b4b949.chapters.id.vtt",
      "en": "proyek-baru.f1f6a334.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.33
      },
      {
        "step": "identitas",
        "start": 9.33,
        "end": 25.81
      },
      {
        "step": "klien-jenis",
        "start": 25.81,
        "end": 48.67
      },
      {
        "step": "produk",
        "start": 48.67,
        "end": 63.99
      },
      {
        "step": "anggaran",
        "start": 63.99,
        "end": 79.21
      },
      {
        "step": "detail",
        "start": 79.21,
        "end": 89.34
      },
      {
        "step": "status",
        "start": 89.34,
        "end": 96.4
      },
      {
        "step": "production-hub",
        "start": 96.4,
        "end": 105.43
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 105.4,
    "version": "50acddac"
  },
  "publikasi-otomatis": {
    "mp4": "publikasi-otomatis.21943fce.mp4",
    "poster": "publikasi-otomatis.21943fce.webp",
    "vtt": {
      "id": "publikasi-otomatis.ea97daad.id.vtt",
      "en": "publikasi-otomatis.6c1ca0c7.en.vtt"
    },
    "chaptersVtt": {
      "id": "publikasi-otomatis.e44cce2b.chapters.id.vtt",
      "en": "publikasi-otomatis.6db98949.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "nyalakan",
        "start": 0,
        "end": 38.91
      },
      {
        "step": "syarat",
        "start": 38.91,
        "end": 48.25
      },
      {
        "step": "status",
        "start": 48.25,
        "end": 60.41
      },
      {
        "step": "terbit",
        "start": 60.41,
        "end": 72.49
      },
      {
        "step": "gagal",
        "start": 72.49,
        "end": 85.9
      },
      {
        "step": "terbitkan-sekarang",
        "start": 85.9,
        "end": 95.27
      },
      {
        "step": "koneksi",
        "start": 95.27,
        "end": 107.6
      }
    ],
    "w": 1280,
    "h": 978,
    "durationSec": 107.6,
    "version": "21943fce"
  },
  "quotation": {
    "mp4": "quotation.e9abcb9b.mp4",
    "poster": "quotation.e9abcb9b.webp",
    "vtt": {
      "id": "quotation.273befc6.id.vtt",
      "en": "quotation.ceb11253.en.vtt"
    },
    "chaptersVtt": {
      "id": "quotation.43976456.chapters.id.vtt",
      "en": "quotation.ffb018ce.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.35
      },
      {
        "step": "klien-proyek",
        "start": 9.35,
        "end": 21.96
      },
      {
        "step": "item",
        "start": 21.96,
        "end": 43.84
      },
      {
        "step": "ppn",
        "start": 43.84,
        "end": 53.89
      },
      {
        "step": "ketentuan",
        "start": 53.89,
        "end": 65.63
      },
      {
        "step": "kirim",
        "start": 65.63,
        "end": 77.36
      },
      {
        "step": "setujui",
        "start": 77.36,
        "end": 87.5
      },
      {
        "step": "disetujui",
        "start": 87.5,
        "end": 99.55
      },
      {
        "step": "revisi",
        "start": 99.55,
        "end": 111.6
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 111.6,
    "version": "e9abcb9b"
  },
  "rencana-konten-klien": {
    "mp4": "rencana-konten-klien.424e484a.mp4",
    "poster": "rencana-konten-klien.424e484a.webp",
    "vtt": {
      "id": "rencana-konten-klien.d0f8aaef.id.vtt",
      "en": "rencana-konten-klien.af000e76.en.vtt"
    },
    "chaptersVtt": {
      "id": "rencana-konten-klien.37b3f5b2.chapters.id.vtt",
      "en": "rencana-konten-klien.7bda4447.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "rencana",
        "start": 0,
        "end": 9.21
      },
      {
        "step": "ponsel",
        "start": 9.21,
        "end": 18.23
      }
    ],
    "w": 540,
    "h": 1168,
    "durationSec": 18.2,
    "version": "424e484a"
  },
  "shot-list": {
    "mp4": "shot-list.a4f43a81.mp4",
    "poster": "shot-list.a4f43a81.webp",
    "vtt": {
      "id": "shot-list.4161cf58.id.vtt",
      "en": "shot-list.ca5a5e63.en.vtt"
    },
    "chaptersVtt": {
      "id": "shot-list.c5c9fc0d.chapters.id.vtt",
      "en": "shot-list.03ebc097.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.3
      },
      {
        "step": "buat",
        "start": 9.3,
        "end": 24.7
      },
      {
        "step": "shot",
        "start": 24.7,
        "end": 66.89
      },
      {
        "step": "urutan",
        "start": 66.89,
        "end": 78.56
      },
      {
        "step": "pdf",
        "start": 78.56,
        "end": 87.77
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 87.8,
    "version": "a4f43a81"
  },
  "vendor-pembelian": {
    "mp4": "vendor-pembelian.43180e0a.mp4",
    "poster": "vendor-pembelian.43180e0a.webp",
    "vtt": {
      "id": "vendor-pembelian.521cf0fc.id.vtt",
      "en": "vendor-pembelian.0139d1fb.en.vtt"
    },
    "chaptersVtt": {
      "id": "vendor-pembelian.314de867.chapters.id.vtt",
      "en": "vendor-pembelian.d0747acd.chapters.en.vtt"
    },
    "chapters": [
      {
        "step": "daftar",
        "start": 0,
        "end": 9.38
      },
      {
        "step": "identitas",
        "start": 9.38,
        "end": 27.45
      },
      {
        "step": "pajak",
        "start": 27.45,
        "end": 37.49
      },
      {
        "step": "bank",
        "start": 37.49,
        "end": 47.55
      },
      {
        "step": "pembelian",
        "start": 47.55,
        "end": 74.84
      },
      {
        "step": "hutang",
        "start": 74.84,
        "end": 86.37
      }
    ],
    "w": 1280,
    "h": 820,
    "durationSec": 86.4,
    "version": "43180e0a"
  }
};
